### ISSUE TITLE
Is this under developement

### ISSUE THREAD

**Issue by kaspar-allenbach** [engram-design/Workflow#1]
Hi.

Are you developing this plugin or is this already dead? I have a website which would need exactly this functionality.

Regards,
K

**Comment by engram-design** [comment]
It's certainly under active development. No ETA I'm afraid, but we'll keep you informed.

**Comment by kaspar-allenbach** [comment]
looking forward to it. If you need a beta tester, contact me.

**Comment by theskyfloor** [comment]
Same. Beta tester / gladly paying customer here!

**Comment by loveevelyn** [comment]
Same!

**Comment by engram-design** [comment]
@kaspar-allenbach @theskyfloor @loveevelyn @jamie-jenks If you're all still interested, the first-look is now available for you to test. Really looking for your feedback as to what your own needs are. The process is pretty simple, but it suits our current needs well.

Be sure to check out the [Wiki](https://github.com/engram-design/Workflow/wiki).

Closing for now - please feel free to open up new issues with feature requests or issues. Cheers!
