### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by umkasanki** [engram-design/Workflow#100]
### Description
When the "Editor Submission Notes Required" option is enabled, an error occurs while submitting for review a record with an empty "Notes about submission" field..

![settings](https://user-images.githubusercontent.com/496132/72701479-7db2f200-3b60-11ea-8062-36ff05509d21.jpg)
![validation](https://user-images.githubusercontent.com/496132/72701480-80154c00-3b60-11ea-9491-fe623bf38fc2.jpg)
![error](https://user-images.githubusercontent.com/496132/72701488-83103c80-3b60-11ea-9bb9-58f3cd2645f7.jpg)
[logs.zip](https://github.com/verbb/workflow/files/4084603/logs.zip)

### Steps to reproduce

1. Change workflow settings
2. Submit for review

### Additional info

- Plugin version: 1.3.3
- Craft version: Pro 3.3.20.1 multisite

**Comment by engram-design** [comment]
Should be fixed in [1.3.4](https://github.com/verbb/workflow/releases/tag/1.3.4)
