### ISSUE TITLE
Error with getSiteById() in Submission.php

### ISSUE THREAD

**Issue by michaelfromtheoutfit** [engram-design/Workflow#103]
### Description
Attempting to upgrade a Craft 2 site to Craft 3.4.4.1. When I go to the Workflow tab (after re-installing the plugin and following the configuration instructions) - I get the following error:

> Argument 1 passed to craft\\services\\Sites::getSiteById() must be of the type int, null given, called in /PATH/TO/MY/STUFF/vendor/verbb/workflow/src/elements/Submission.php on line 306"}

### Steps to reproduce

1. Upgrade Craft to 3.4.4.1 from Craft 2
2. Install Workflow via control panel
3. Click "Workflow" tab.

### Additional info

- Plugin version: 1.4.1
- Craft version: 3.4.4.1
- PHP Version: 7.3.9

**Comment by engram-design** [comment]
Should be fixed in [1.4.2](https://github.com/verbb/workflow/releases/tag/1.4.2)
