### ISSUE TITLE
Question: how many submission notes are kept? Is it a number thing or they time out?

### ISSUE THREAD

**Issue by jlcharette** [engram-design/Workflow#104]
Greetings,

I would like to know how many submission notes are kept? Do they eventually get removed from the overview list? I couldn't find answer to my question in the documentation.

Thank you!

**Comment by engram-design** [comment]
There's no limit to how many notes on submissions are kept. In terms of the submissions themselves, they're kept indefinitely, so you have a record of the approval process of particular entries. You can delete submissions through the Workflow settings
