### ISSUE TITLE
Question: How can I edit the submission inside the `EVENT_BEFORE_SAVE` hook?

### ISSUE THREAD

**Issue by dictions** [engram-design/Workflow#105]
How can I edit the submission inside the `EVENT_BEFORE_SAVE` hook?

I'd like to read some info about the entry, make a request, and save some extra info to the submission to use in the publisher email.

**Comment by engram-design** [comment]
Refer to the events docs - https://verbb.io/craft-plugins/workflow/docs/developers/events#the-beforeSaveSubmission-event

```
use verbb\workflow\elements\Submission;
use yii\base\Event;

Event::on(Submission::class, Submission::EVENT_BEFORE_SAVE, function(Event $e) {
    $submission = $event->sender;

    // Update model attributes
    $submission->editorNotes = 'Some new note';

    // Save it back to the event
    $event->sender = $submission;
});
```

But, there are also email events that might be more suitable in your case?
