### ISSUE TITLE
Draft changes are lost when editor submits without comment

### ISSUE THREAD

**Issue by jujubh** [engram-design/Workflow#106]
### Description

If editor notes are required any changes the editor has made to a draft are lost when they submit without a note unless they have explicitly saved the draft prior to to submitting for review. 

### Steps to reproduce

1. Enable editor notes are required.
2. Make changes to a draft.
3. Submit for review without adding a note.

### Additional info

- Plugin version: 1.4.2
- Craft version: 3.4.9

**Comment by engram-design** [comment]
Should be fixed in [1.4.3](https://github.com/verbb/workflow/releases/tag/1.4.3)
