### ISSUE TITLE
Error after save when setting Editor and Publisher

### ISSUE THREAD

**Issue by jbrew30** [engram-design/Workflow#107]
### Description
I'm getting this error when I set the User Group in the settings.

Failed to report exception due to missing client key (DSN)

yii\base\NotSupportedException: Changes to the project config are not possible while in read-only mode. in /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/craftcms/cms/src/services/ProjectConfig.php:441
Stack trace:
#0 /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/craftcms/cms/src/services/Plugins.php(705): craft\services\ProjectConfig->set('plugins.workflo...', Array, 'Change settings...')
#1 /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/verbb/workflow/src/controllers/BaseController.php(56): craft\services\Plugins->savePluginSettings(Object(verbb\workflow\Workflow), Array)
#2 [internal function]: verbb\workflow\controllers\BaseController->actionSavePluginSettings()
#3 /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-plugin-set...', Array)
#6 /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-plugin-set...', Array)
#7 /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('workflow/base/s...', Array)
#8 /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('workflow/base/s...', Array)
#9 /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /opt/rh/httpd24/root/var/www/trees/goml-refresh/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /opt/rh/httpd24/root/var/www/trees/goml-refresh/web/index.php(21): yii\base\Application->run()
#12 {main}

### Steps to reproduce

1. Go to General Settings
2. Apply user groups to dropdowns
3. Click Save

### Additional info

- Plugin version: 1.4.5
- Craft version: 3.4.13

**Comment by engram-design** [comment]
Right, so you shouldn't be able to access the settings page at all if `allowAdminChanges = false`, which is the reason for this error (I believe).

This should be corrected in [1.4.6](https://github.com/verbb/workflow/releases/tag/1.4.6)

**Comment by jbrew30** [comment]
That is correct and thank you.
