### ISSUE TITLE
Multiple Submissions showing from an Editor creating a single new entry.

### ISSUE THREAD

**Issue by masonry47** [engram-design/Workflow#109]
### Description
Hi there, 

We are having an issue with multiple submissions showing on a single save (see attachment).  The number of submissions that show varies between 2 and 5  (and therefore fires off the same number of notifications emails )and the URLs of each submission point towards (either) the "current" version of the entry like this

/admin/entries/section-handle/1095613-entry-title?site=default

or the draft version 

/admin/entries/section-handle/1095613-entry-title?site=default&draftId=12282 (which is the one we would expect)

It only happens when editor is creating a new entry and submitting through WorkFlow.  If they edit an already published entry, all behavior is normal.

### Steps to reproduce

1. Editor logins in and creates new entry and clicks "save draft and submit for review"

### Additional info

- Plugin version:1.4.6
- Craft version:3.4.18

We recently updated from Craft 3.3.20 and 1.23 of Workflow (and all worked fine), which is when this started. Also just some FYIs, we are using multi site (localized website in multiple languages).  We have tried backtracking on the version, uninstalling and re-installing, disabling all plugins, checked the logs which do not report anything (error wise at lease).

<img width="802" alt="Screen Shot 2020-05-07 at 4 41 22 PM" src="https://user-images.githubusercontent.com/48130527/81348795-64d53a80-9084-11ea-8dc8-042275fa4aca.png">

Thank you!

**Comment by engram-design** [comment]
This looks to be an issue with https://plugins.craftcms.com/preparse-field and will continue investigating.
