### ISSUE TITLE
Required Fills Not Being Filled out Throws Error

### ISSUE THREAD

**Issue by masonry47** [engram-design/Workflow#111]
### Description
When publisher "approves and publishes" an entry that has required fields that are not filled out, you get a server error "Call to a member function send() on null" rather than normal validation.  

The problem starts with the editor submitting a new entry for approval without required fields filled in.  I think the only reason they can even submit the entry without required fields is because the entry status is defaulted to disabled so Craft allows the entry to be "Created"

So at the point the publisher has an entry without all of the fields filled in and cannot edit the entry because it is locked.  Regardless of if they know there sare some required fields or not, they submit and get "Call to a member function send() on null"

Thanks!

### Steps to reproduce

1. editor creates a new entry and submits for approval without filling out all required fields.
2. publisher "submits and approves"

### Additional info

- Plugin version: 1.4.6
- Craft version: 3.4.17

**Comment by engram-design** [comment]
Required fields should be validated when you submit it for review. An editor isn't supposed to be able to submit it for review, even if it is disabled, so I'll check this.

**Comment by engram-design** [comment]
This should be fixed in [1.4.7](https://github.com/verbb/workflow/releases/tag/1.4.7)
