### ISSUE TITLE
Date Approved does not apply the application timezone

### ISSUE THREAD

**Issue by FrancisMawn** [engram-design/Workflow#112]
### Description
When a publisher approves a submission, the approved date doesn't apply the application timezone which results in some data discrepancy.

**services\Submissions line 112:**
```$submission->dateApproved = new \DateTime;```

This could to be the issue? While digging in CraftCMS code, I've noticed they seem to be using some kind of DateTimeHelper class to manage their timestamps. 

### Steps to reproduce

1. As an editor user, submit a modification to be approved.
2. As a publisher user, use the workflow widget on the entry page to approve and publish the submission.
3. Browse to the Workflow dashboard. The approved date does not reflect the application timezone setting.

### Additional info

- Plugin version: 1.4.6
- Craft version: 3.4.18

**Comment by engram-design** [comment]
Fixed in [1.4.8](https://github.com/verbb/workflow/releases/tag/1.4.8)
