### ISSUE TITLE
SQL error: table 'workflow_reviews' doesn't exist

### ISSUE THREAD

**Issue by martyspain** [engram-design/Workflow#115]
### Description

When submitting an entry as an author, a SQL error is shown stating that the table 'workflow_reviews' does not exist. 

`Database Exception – yii\db\Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.workflow_reviews' doesn't exist
The SQL being executed was: SELECT *
FROM 'workflow_reviews'
WHERE ('submissionId'=917856) AND ('approved'=TRUE)
ORDER BY 'dateCreated'
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'xxx.workflow_reviews' doesn't exist
)
↵
Caused by: PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.workflow_reviews' doesn't exist
in /Development/xxx/vendor/yiisoft/yii2/db/Command.php at line 1293`

I've had a quick look through the source code for the 1.5.0 release, and it seems that there's a missing migration to set up the table for the new reviews functionality. If you install the plugin from scratch, it's there, but if you update from a previous version, the table is not created.

### Steps to reproduce

1. Begin with an existing Workflow install at 1.4.8
2. Update to 1.5.0
3. Submit an entry as an author to a section that has Workflow enabled
4. A database error is shown

### Additional info

- Plugin version: 1.5.0
- Craft version: 3.4.19.1

**Comment by engram-design** [comment]
Not sure how I missed this, should be fixed in [1.5.1](https://github.com/verbb/workflow/releases/tag/1.5.1)

**Comment by martyspain** [comment]
@engram-design Did the new migration file get added to the 1.5.1 release? There doesn't seem to be any difference between the two versions at the moment.

**Comment by engram-design** [comment]
Sorry, updated the release now.
