### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by outline4** [engram-design/Workflow#118]
Hi Verbb, 

I migrated from Craft version 2 to version 3.4

Before the upgrade I was able to translate almost every aspect of the plugin within the file `craft/config/translations/de.php`. 

Now, when looking into `vendor/verbb/workflow/src/translations/en/workflow.php`  I can only see strings that relate to the emails that get send. 

I translated a lot of stuff in the craft v2 version of workflow: 

E.g.: 

    "Entry submitted for approval." => "Eintrag wurde zur Überprüfung eingereicht.",
    "Could not submit for approval." => "Eintrag konnte nicht zur Überprüfung eingereicht werden.",
    "Submission revoked." => "Eintrag wurde zurückgezogen.",
    "Could not revoke submission." => "Konnte Eintrag nicht zurückziehen",
    "Entry approved and published." => "Eintrag genehmigt und publiziert.",
    "Could not approve and publish." => "Konnte Eintrag nicht genehmigen und publizieren.",
    "Submission rejected." => "Eintrag abgelehnt.",
    "Could not reject submission." => "Konnte Eintrag nicht ablehnen.",
    "Workflow Submission" => "Workflow Eintrag",
    "Rejected" => "Abgelehnt",
    "Revoked" => "Widerrufen",
    "All Submissions" => "Alle Einträge",
    "Editor" => "Editor",
    "Date Submitted" => "Date Submitted",
    "Publisher" => "Publisher",
    "Date Approved" => "Datum angenommen",
    "Date Rejected" => "Datum abgelehnt",
    "Approved submission" => "Eintrag wurde überprüft",
    "approved this entry on {date}." => "hat am {date} den Eintrag bestätigt.",
    "Rejected submission" => "Rejected submission",
    "rejected this entry on {date}." => "Eintrag abgelehnt am {date}.",

    "Awaiting approval" => "Eintrag wartet auf Überprüfung",
    "This entry has been submitted for review on {date} and is awaiting approval. Changes cannot be made until approved." => "Dieser Eintrag wurde am {date} zur Überprüfung eingereicht. Es können bis zur Bestätigung keine Änderungen gemacht werden.",
    "Revoke submission" => "Eintrag zurückziehen",
    "Revoked submission" => "Zurückgezogene Einträge",
    "revoked this entry on {date}." => "hat am {date} den Eintrag zurückgezogen.",

    "Submit for review" => "Zur Überprüfung senden",
    "Submitting this entry for review will lock further edits and notify your publisher that this entry is ready for approval." => "Wenn Sie diesen Eintrag zur Überprüfung senden dann wird der Eintrag eingefroren bis ihn der Publisher ihn freigegeben hat.",
    "Notes about your response." => "Notizen über die Antwort.",
    "revoked this submission on {date}." => "hat den Eintrag am {date} zurückgezogen.",
    "Submission awaiting approval" => "Eintrag wartet auf Bestätigung",
    "has submitted this entry for review on {date}. Please review this entry before publishing." => "hat den Eintrag am {date} zur Überprüfung gesendet. Bitte kontrolliere den Eintrag und schalte ihn anschliessend frei.",
    "Approve & publish entry" => "Eintrag frei schalten",
    "Reject" => "Ablehnen",
    "Drafts" => "Entwürfe",
    "Date created" => "Erstellt am",
    "Date updated" => "Geändert am",
    "No draft entries." => "Keine Entwürfe.",
    "Enabled Sections" => "Aktivierte Sektionen",
    "Select which sections you require editor-publisher workflow enabled for." => "Wähle die Sektionen aus für welche du das Workflow Tool aktivieren willst.",
    "Editor User Group" => "Editoren Mitgliedergruppe",
    "Select the user group that your editors belong to. Editors are users that can edit content, but not publish live." => "Wähle die Benutzergruppe aus zu welcher die Editoren gehören. Sie können Einträge erfassen, aber nicht frei schalten.",
    "Publisher User Group" => "Publisher Mitgliedergruppe",
    "Select the user group that your publishers belong to. Publishers are users who are notified when an editor submits content for review, and can approve content to be published live." => "Wähle die Mitgliedergruppe aus zur welcher die Publisher gehören. Publisher werden per Email benachrichtigt wenn es einen Eintrag zu bestätigen gibt. Sie können Einträge frei schalten.",

When I try to put these strings into `config/translations/de/workflow.php` it won't translate anything. 

Could you please help me with translating this plugin. 
It's rather important for us, since we wrote a manual in German. 

Any help highly appreciated! 

### Additional info

- Plugin version: 1.5.1
- Craft version: 3.4.22.1

**Comment by engram-design** [comment]
It looks like those translations were only part of your local project, and not part of the Workflow plugin? See the [Craft 2 translations folder](https://github.com/verbb/workflow/tree/craft-2/workflow/translations).

As an aside - I'd be very happy to roll these into the plugin, unless they're site-specific.

I believe you need to place them in `translations/de/workflow.php`, outside of the config folder. Refer to [docs](https://docs.craftcms.com/v3/static-translations.html#provide-the-translations)

**Comment by outline4** [comment]
Thanks for the hint with the translation folder.  
That did the trick.  
Unlucky, most strings changed and my translation is not very general. Although most of the stuff is correct. 

It would be a great idea to have more generic strings to be able to translate them. Much like you did for the emails. If that's the case, I would happily translate them. 

Cheers 
Stefan

**Comment by stephanedemotte** [comment]
Hello, Any news ? We need workflow in french ...
How can we translate all the plugins string ?

**Comment by engram-design** [comment]
At some point, we'll look at using Crowdin for our plugins. For now, you can create [static translations](https://craftcms.com/docs/3.x/sites.html#provide-the-translations) for French. While we don't have a single output of all english texts, you can generate this yourself from one of the [many plugins](https://plugins.craftcms.com/search?q=translations&tab=plugins) available.
