### ISSUE TITLE
Entries don't add if adding to a parent that is disabled

### ISSUE THREAD

**Issue by green17** [engram-design/Workflow#119]
### Description
Entries don't add if adding to a parent entry that is disabled. If the parent entry is enabled it works fine. If WorkFlow is disabled all works fine again too.

### Steps to reproduce

1. Add new entire 
2. Pick a parent 
3. Save

This will add an entire that does not show in the structure/section anywhere. It does show in 'All entries' but you can not edit the page gives 'HTTP 404 – Not Found – yii\web\NotFoundHttpException *Entry not found*' - how would how to remove these now?

### Additional info

- Plugin version: Workflow 1.5.3
- Craft version: Craft Pro 3.4.23 
- PHP 7.2.31

**Comment by engram-design** [comment]
That seems like very odd behaviour. The parent (whether disabled or enabled) shouldn't have much bearing over what Workflow does. In fact, I've just tested it myself a few times, and it seems to work as expected.

You mention you hit "Save" - do you mean Craft's native "Create" button, or Workflow's "Save draft and submit for review". I've tried both.

Can you outline your steps any further to clarify? When you hit "Create", that should take you out to the entries index - the entry just isn't there?

**Comment by green17** [comment]
I have retested this in Craft 3.5.7 and all is working fine now @engram-design - thanks for your help - apologies for the late reply.

Plugin version: Workflow 1.5.6
Craft version: Craft Pro 3.5.7
PHP 7.2.31
