### ISSUE TITLE
Rejecting a submission emails everyone in Editors permission group.

### ISSUE THREAD

**Issue by julzmon** [engram-design/Workflow#12]
Rejecting a submission emails everyone in Editors permission group. Is this the intended behavior? Would be nice if email was sent only to the person creating the draft which needs approval.

**Comment by engram-design** [comment]
Yeah - that was a little bit of an oversight on my behalf. This'll be changed/fixed in the next release.

**Comment by engram-design** [comment]
Fixed in [0.9.4](https://github.com/engram-design/Workflow/releases/tag/0.9.4)
