### ISSUE TITLE
Submitting another author's draft takes a lot of time.

### ISSUE THREAD

**Issue by jlcharette** [engram-design/Workflow#121]
### Description

Submitting another editor's draft takes a lot of time. The process is much faster when submitting your own draft.

### Steps to reproduce

1. Edit another author's draft.
2. Submit for review.

### Additional info

- Plugin version: 1.5.4
- Craft version: 3.4.28.1

**Comment by engram-design** [comment]
I've tried on several instances to try and replicate this, but have been unable to do so. Do you have any custom modules that could be interfering with the saving of entries? Or any plugins?

Functionally, there shouldn't be any difference if you're submitting your own, or another persons draft.

**Comment by jlcharette** [comment]
I will test on a fresh install with only Workflow installed to figure out if another plugin/module is interfering.

**Comment by jlcharette** [comment]
I tried on a fresh environment with only workflow installed, and everything works fine. Must be another plugin interfering as you suggested.

**Comment by engram-design** [comment]
Interesting. Can you send through a list of installed plugins? Do you have any custom modules?

Might be easier to send through your composer.json and composer.lock files if you can
