### ISSUE TITLE
Wrong Site in notification emails

### ISSUE THREAD

**Issue by pierrestoffe** [engram-design/Workflow#122]
### Description

A client of ours has reported that the email notifications did not include the correct Site information. If the default Site in my Craft install is named "English" but the entry was edited in the "Korean" Site, the email notification will mention a submission for approval on the "English" Site instead of the "Korean" Site.

This is only an issue in the content of the email → the correct Site is displayed in the "Site" column of the "Workflow overview" table.

### Steps to reproduce

1. Edit an entry in a non-default Site
2. Submit for approval
3. Check your emails

### Additional info

- Plugin version: 1.5.4
- Craft version: 3.4.29

**Comment by engram-design** [comment]
The default email templates use `{{ siteName }}` which I believe resolves to your primary site. You can of course change this to your needs [see docs](https://verbb.io/craft-plugins/workflow/docs/template-guides/email-notifications)

You could replace `{{ siteName }}` with `{{ submission.owner.site.name }}`

**Comment by pierrestoffe** [comment]
Sorry, I completely missed that section of the docs. Very clear.
I still wonder if that shouldn't be the default value though.

**Comment by engram-design** [comment]
Yep, I'll consider adding it to the default!
