### ISSUE TITLE
approval status in entries table view

### ISSUE THREAD

**Issue by piffpaffpuff** [engram-design/Workflow#123]
**What are you trying to do?**
as a user i send in an entry for approval. now i would like to know what is the status of the approval without opening the detail view of an entry.

**What's your proposed solution?**
it would be nice to show/hide a "approval status" column in the entries view. like that a submitter has an overview of the entries that were already approved

**Comment by engram-design** [comment]
Added in [2.0.0-beta.8](https://github.com/verbb/workflow/releases/tag/2.0.0-beta.8)
