### ISSUE TITLE
Merge changes into draft causing Error 500, calling unknown method message

### ISSUE THREAD

**Issue by bliswebagency** [engram-design/Workflow#125]
**Description**
Editor saves draft and requests approval. Publisher, without approving, saves and publishes the same entry. Then goes to editor's draft to merge changes causes following:

Error 500 occurs with the following response
{"error":"Calling unknown method: verbb\\workflow\\elements\\Submission::ownerId()"}

**Steps to reproduce**
1. Editor saves draft, requests approval
2. Publisher edits and publishes same entry
3. Publisher merges their changes with editor's draft

**Additional info**
- Plugin version: 1.5.5
- Craft version: 3.5.6
- Multi-site: Yes

**Additional context**
On some occasion, if there are multiple drafts, merging with one of the drafts results in no error, but then merging with another it returns a 500.

**Comment by engram-design** [comment]
Can you try with [1.5.6](https://github.com/verbb/workflow/releases/tag/1.5.6) that should've fixed this error?

**Comment by bliswebagency** [comment]
Thank you for the update. We will give it a try and keep you posted.

**Comment by bliswebagency** [comment]
> Can you try with [1.5.6](https://github.com/verbb/workflow/releases/tag/1.5.6) that should've fixed this error?

We were able to successfully do a merge under the original conditions. We have asked our client to do further testing on their systems but it looks like this fix is working. Thank you very much for the fast response.
