### ISSUE TITLE
[Deleted element] no information on what entry?

### ISSUE THREAD

**Issue by green17** [engram-design/Workflow#128]
**Description**
There is a number of rows saying [Deleted element] in the CP there is no information on what entry or a link?

Should you be able to click and see what the user has suggested to deleted in the entry and approve or not?

**Comment by engram-design** [comment]
This means that the draft element was deleted, so there's no entry to link to anymore. This isn't referring to content in the entry that's been deleted

**Comment by green17** [comment]
@engram-design thanks, would it help to change the wording of it to maybe 'Draft deleted'?

**Comment by gbowne-quickbase** [comment]
We see this behaviour when an image has been added to an entry, and that's all that's been changed. 
![image](https://user-images.githubusercontent.com/39066452/117037758-d5815800-acd4-11eb-9fed-d071d230367d.png)

**Comment by engram-design** [comment]
This has been improved in [2.0.0-beta.8](https://github.com/verbb/workflow/releases/tag/2.0.0-beta.8) now that we're saving the original canonical entry, which is switched back to once the draft has been applied (and therefore deleted).
