### ISSUE TITLE
Option to duplicate an entry as a draft for editors

### ISSUE THREAD

**Issue by green17** [engram-design/Workflow#130]
It would be good for editors to be able to duplicate an entry as a draft - currently, editors cannot do this as there is only the option to 'save as new' which they do not have access to as editors.

**Comment by engram-design** [comment]
I'd say this is almost a feature request for Craft itself? We're using the permissions built into Craft to determine if users can create/edit/delete entries (and drafts).

**Comment by green17** [comment]
Thanks @engram-design we add this to a plugin to do it on the admin list - I put the info up here if anyone needs:
https://craftcms.stackexchange.com/questions/36562/is-it-possible-to-duplicate-an-entry-as-not-enabled-live-from-the-listing-page/36563#36563

**Comment by engram-design** [comment]
Thanks for following up with that example, as such will close this issue. I'm pretty certain this should be a Craft core concern, which will hopefully make its way into Craft in the future.
