### ISSUE TITLE
GraphQL API to fetch the review status of an entry

### ISSUE THREAD

**Issue by kruncher** [engram-design/Workflow#131]
**What are you trying to do?**
Fetch the review status of entries to use in a CI pipeline.

**What's your proposed solution?**
To be able to use a GraphQL API such as:

```graphql
pendingReviews {
    entryId
    draftId
    status
}
```

**Comment by engram-design** [comment]
Added in [2.0.0-beta.8](https://github.com/verbb/workflow/releases/tag/2.0.0-beta.8). Refer to the [docs](https://verbb.io/craft-plugins/workflow/docs/developers/graphql)
