### ISSUE TITLE
Peer review process ("four-eye check")

### ISSUE THREAD

**Issue by benatleith** [engram-design/Workflow#132]
**What are you trying to do?**

In small teams we find it's often the case that content managers need to act as both editors and publishers depending on context (specialist areas of knowledge, covering for colleagues on vacation etc). Trying to shoehorn these users into _either_ an editor _or_ a publisher role at any given time isn't practical. What is needed is a "four-eye check" i.e. peer review process.

**What's your proposed solution?**

How this could work in practice is that any user in a 'content workflow' group:

* can submit a change for review
* can receive a change for review
* can publish a change (EXCEPT if they themselves submitted the change)
* cannot publish a change that hasn't been through the workflow

We've tried to implement a limited version of this by creating Editor and Publisher roles and assigning both roles to a user. Unfortunately this seems to allow users to bypass the workflow completely, and the audit trail of who did what and when is missing.

**Comment by engram-design** [comment]
I'm just circling back to this. If a user belongs to both user groups, they shouldn't have the opportunity to approve their own submission. The sidebar pane will show the editor pane as a priority, even if they are in both groups. This will show the submission is still waiting for approval.

I suppose the only method allowing approval is by going to Workflow > Submission and approving from there. Does that sounds right?

**Comment by benatleith** [comment]
Hi @engram-design - yes that sounds right.

**Comment by engram-design** [comment]
Should be fixed in [1.6.2](https://github.com/verbb/workflow/releases/tag/1.6.2)
