### ISSUE TITLE
Submission approval stalling

### ISSUE THREAD

**Issue by leightonhughes** [engram-design/Workflow#134]
**Description**

From client:
I'm getting an internal server error when approving an article submission. The first time it happened I exited the page and reopened the article, and it was able to save the changes I made. However, when I added my notes and then hit the approve and publish button, the same internal server error appeared.

I just tried it again and it said internal server error, BUT the approval email went through.

--
Unfortunately can't supply any logs at the moment as temp locked out of the prod server.

**Additional info**
- Plugin version: 1.6.2
- Craft version: 3.7.10
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Would love to get some more information on your logs, as I can't replicate that on my end. Keen to know what exactly is the error - so be sure to check the `/storage/logs/web.log`, `/storage/logs/workflow.log` and `/storage/logs/phperrors.log` files.

It might be related to email notifications, if you're finding things stalling?

**Comment by leightonhughes** [comment]
Thanks Josh. I rolled back to 1.6.1 and working fine again. Will check out those logs and get back to you.

**Comment by engram-design** [comment]
Interesting. The only [change](https://github.com/verbb/workflow/commit/7718db5aad88d3c5a37c6336eaf743b93da61f41) was fixing some behaviour when using the element actions under Workflow > status dropdown > approve - is your client using this method for approving submissions?

**Comment by leightonhughes** [comment]
I've managed to pinpoint the issue to be with when the blitz plugin is enabled. Would you be able to test with it enabled and see if it stalls for you as well.

Craft version: 3.7.12
Workflow version: 1.6.2
Blitz version: 3.10.3

**Comment by leightonhughes** [comment]
Hey Josh, just some more info on this. What I've discovered is that the "Upload a file" allows assets to go directly to the volume in the draft entry state before it has been created. This allows a publisher to approve the entry.

If an asset is added via "Add an asset" it goes to the users temp folder and errors out when a publisher approves as the image can't be found. In #9619 the temp folder looks to be correct functionality if in draft, so how is a publisher meant to approve in that case?

**Comment by engram-design** [comment]
So I've tested with Blitz, and there's certainly no lag going on, which isn't surprising seeing as though this is in the control panel, where Blitz shouldn't really have too much say. Any JS errors? Tried with `devMode = true`?

So uploading assets - that seems expected behaviour for a draft in Craft (without Workflow)? When you upload a file, it's immediately added to the temp folder, even if you haven't saved the draft entry yet. The "Upload a file" and "Add an asset" are the same functionality (if by that you mean uploading a file through the asset-select modal). Picking an existing asset should be fine, and I don't believe it'll relocate it.

**Comment by leightonhughes** [comment]
Thanks for testing it out Josh. Yes tried devMode true. Was able to get an error on Friday to do with database locking. Not sure if this is the cause or effect. I've just sent it to you on discord. I'm also wondering whether this lag is related to #135.
Discussing the assets with a craft support guy this evening as finding upload through the "Upload a file" button are skipping temp as you mention. Client is dragging and dropping onto the upload a file I think.

**Comment by engram-design** [comment]
@leightonhughes Interesting on the upload file button, I thought it was completely the same process. But, I believe unrelated to Workflow. Will follow up on Discord.
