### ISSUE TITLE
The '(required)' label in the placeholder for submission notes is not translatable

### ISSUE THREAD

**Issue by MoritzLost** [engram-design/Workflow#137]
**Description**

The placeholder for the input field for editor submission notes includes a placeholder `{required}` which is either `'(required)'` or an empty string, depending on the setting. While the placeholder itself is translatable (source string: `'Notes about your submission {required}'`), the ` (required)` string is not translatable. So the translation can't include that placeholder as it won't be in the correct language. Making that string translatable as well would solve this issue.

Current template:

```twig
{% set required = settings.editorNotesRequired ? ' (required)' : '' %}
```

Suggested change:

```twig
{% set required = settings.editorNotesRequired ? ' (required)'|t('workflow') : '' %}
```

See [src/templates/_includes/editor-pane.html](https://github.com/verbb/workflow/blob/craft-3/src/templates/_includes/editor-pane.html). The same change should be applied to [src/templates/_includes/publisher-pane.html](https://github.com/verbb/workflow/blob/craft-3/src/templates/_includes/publisher-pane.html).

**EDIT: Small bug in the publisher pane**

I found that the publisher pane template does something slightly different, but it's buggy so the placeholder is currently not translatable at all:

```twig
'Notes about your response' ~ required ~ '.' | t('workflow'),
```

This is probably meant to make the string with and without the `(required)` suffix translatable. However, the filter operator (`|`) has a higher precedence than string concatenation (`~`), so the only thing that gets translated is the dot at the end.

Putting the concatenated string in parentheses solves this issue:

```twig
('Notes about your response' ~ required ~ '.') | t('workflow'),
```

Personally, I even prefer this approach to my suggested solution above, so maybe this (fixed) approach could be incorporated into the editor pane template as well? 

[Source](https://github.com/verbb/workflow/blob/craft-3/src/templates/_includes/publisher-pane.html#L51)

**Additional info**

- Plugin version: 1.6.2
- Craft version: 3.7.13

**Comment by engram-design** [comment]
Good pickup. I've actually simplified it to two different strings, just to save a bit of heartache dealing with translating strings like ` (required)` on their own. Now there are the following strings to translate:

```
Notes about your response
Notes about your response (required)
Notes about your submission
Notes about your submission (required)
```

Fixed in [1.6.3](https://github.com/verbb/workflow/releases/tag/1.6.3)
