### ISSUE TITLE
The date format is hardcoded and doesn't work for different languages

### ISSUE THREAD

**Issue by MoritzLost** [engram-design/Workflow#138]
**Description**

There are multiple translations that include a date and time (for example, the date and time of a submission). All of those translations receive the date and time as a formatted string. The problem is that the string is hardcoded to a specific format (`'jS M Y g:ia'`) which doesn't work well in different languages. For example:

```twig
<p>{{ submission.editorUrl | raw }} {{ "submitted this entry for review on {date}. Please review this entry before publishing." | t('workflow', { date: submission.dateCreated | date('jS M Y g:ia') }) }}</p>
```

Given a German translation, this results in a really awkward sentence:

> Admin hat diese Einreichung am 23rd Sept. 2021 3:01pm zurückgenommen.

**Suggested solutions**

Instead of hard-coding a specific format, those translations could use the [datetime filter with one of the predefined formats](https://craftcms.com/docs/3.x/dev/filters.html#datetime), those are locale-aware by default:

```twig
<p>{{ submission.editorUrl | raw }} {{ "revoked this entry on {date}." | t('workflow', { date: submission.dateRevoked | datetime('medium') }) }}</p>
```

This results in a much better translation:

> Admin hat diese Einreichung am 23.09.2021, 15:01:48 zurückgenommen.

Another option would be to add a setting to make the datetime format configurable, though using the predefined formats would be sufficient in my opinion.

**Additional info**

- Plugin version: 1.6.2
- Craft version: 3.7.13

**Comment by engram-design** [comment]
Yep, great point. I believe this might've been carried over from way back when these localised helpers for formatting didn't exist. We'll keep the configurable option for down the track, so have just adjusted according to your feedback.

Fixed in [1.6.3](https://github.com/verbb/workflow/releases/tag/1.6.3)

**Comment by MoritzLost** [comment]
@engram-design Thanks for the quick response! The fix is working well. Though I noticed you're using the `date` filter instead of `datetime`, so now only the date is displayed. Wouldn't it be better to display the time as well? The datetime filter supports predefined formats as well, so this would still work well in all languages.

1.6.3:

```twig
<p>{{ url | raw }} {{ "rejected this entry on {date}." | t('workflow', { date: submission.dateRejected | date('medium') }) }}</p>
```

Using `datetime`:

```twig
<p>{{ url | raw }} {{ "rejected this entry on {date}." | t('workflow', { date: submission.dateRejected | datetime('medium') }) }}</p>
```

**Comment by engram-design** [comment]
Whoops - yep, too quick to apply that fix! Fixed for the next release. To get the fix early, change your `verbb/workflow` requirement in `composer.json` to:

```
"require": {
  "verbb/workflow": "dev-craft-3 as 1.6.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by MoritzLost** [comment]
@engram-design Thanks for the fix!
Another minor bug, the 'Notes about your submission' line is now missing the `t` filter, so it isn't translatable right now, see here: https://github.com/verbb/workflow/blob/craft-3/src/templates/_includes/editor-pane.html#L30-L33

Could you update that for the next release as well? Thanks!

**Comment by engram-design** [comment]
Sorry about that, all done in [1.6.4](https://github.com/verbb/workflow/releases/tag/1.6.4)
