### ISSUE TITLE
Docs say to use IDs in config file, but expects UIDs

### ISSUE THREAD

**Issue by GaryReckard** [engram-design/Workflow#142]
**Description**
In the docs for configuration (https://verbb.io/craft-plugins/workflow/docs/get-started/configuration) it says to specify the "User Group ID", "User IDs", and "section ID". When I tried using the IDs, my settings were not working. When I tried using UID, instead, they did work.

I noticed in https://github.com/verbb/workflow/blob/71ac456f5ed9866ef590ad5a3ae9883efe83dce2/src/services/Service.php#L280 and https://github.com/verbb/workflow/blob/71ac456f5ed9866ef590ad5a3ae9883efe83dce2/src/services/Service.php#L222-L223 it is expecting UIDs and converting them to IDs.

I think the docs need to be updated to specify that UIDs should be utilized rather than IDs.

**Additional info**
- Plugin version: 1.6.5
- Craft version: 3.7.21
- Multi-site: Yes

**Comment by engram-design** [comment]
Yep, sorry about that - the docs needed to be updated to refer to UIDs. This was previously the case, but we should be using UIDs instead of IDs since project config renders that unreliable.

Updated.

**Comment by GaryReckard** [comment]
Awesome, thanks @engram-design !

It looks like `selectedPublishers ` actually still expects an ID rather than a UID: https://github.com/verbb/workflow/blob/69c769debde6572e3b40b33c5230f6b613ea4f0a/src/services/Submissions.php#L435

**Comment by engram-design** [comment]
@GaryReckard Right you are!
