### ISSUE TITLE
Finer-grained control over publisher notifications, or EVENT for customization of publishers to notify

### ISSUE THREAD

**Issue by GaryReckard** [engram-design/Workflow#143]
**What are you trying to do?**
We need to have different workflows for different sections. For instance, we have a "People" section, and a "Team Pages" section. We have user groups like "People Editor" and "People Publisher", and "Team Pages Editor" and "Team Pages Publisher", with the appropriate permissions to create drafts, and publish those entries, respectively. In Workflow, we have a "Workflow Editor" and "Workflow Publisher" user groups set up. 

For users who can create "People" drafts, we have them in "People Editor" AND "Workflow Editor" groups. And for users who can publish those, we have them in "People Publisher" and "Workflow Publisher" groups, etc.

**What's your proposed solution?**
It would be great if we could specify that drafts submitted by users in the "People Editor" group would go to Workflow Publishers in the "People Publisher" group, for instance. 

Or, perhaps if we could specify rules for each "Enabled Section" as to where notifications would go (specific user group or specific users).

Or, perhaps if we could just have an `EVENT` that we could use, somewhere in this function https://github.com/verbb/workflow/blob/50b6bd44db7c57154a529e57fdcdf80e99754343/src/services/Submissions.php#L398-L447
... where we could use our own logic to determine the list of Publishers to notify.

**Comment by GaryReckard** [comment]
I noticed the `EVENT_BEFORE_SEND_PUBLISHER_EMAIL` event hook within the `$publishers` for loop. However, I'm not sure how I would prevent the following `$mail->send();`. And if I could, this would still require looping through all publishers, which seems wasteful.

If I had an event to tie into before that loop, where I could either provide custom 'selectedPublishers' based on my own rules, given the `$submission` object, I think I could accomplish what I need here.

**Comment by engram-design** [comment]
Yep that use-case sounds pretty solid. I'm not quite sure how best to handle that from a UI point of view (I'll give it some thought), but an event is certainly doable.

The `EVENT_BEFORE_SEND_PUBLISHER_EMAIL` is there, but it's not cancelable - but I'll make that change (also to all other before-email events).

I've also added a few more events for you to set the publisher/reviews/editor users before getting to these events, which is along the lines of what you'll want. `EVENT_PREPARE_PUBLISHER_EMAIL` in your case. So I believe you should be able to use either event to achieve this.

To get these updates early, change your `verbb/workflow` requirement in `composer.json` to:

```
"require": {
  "verbb/workflow": "dev-craft-3 as 1.6.6",
  "...": "..."
}
```

Then run `composer update`. See the updated docs https://verbb.io/craft-plugins/workflow/docs/developers/events#the-prepareEditorEmail-event

**Comment by engram-design** [comment]
Added in [1.7.0](https://github.com/verbb/workflow/releases/tag/1.7.0)
