### ISSUE TITLE
Entire editor group is notified of entry approval

### ISSUE THREAD

**Issue by JamesMcFall** [engram-design/Workflow#15]
Hey Josh!
Thanks for the plugin, it's amazing. It's saved me a lot of time and given a super slick solution for a client.

I've ran into an issue though. When a publisher approves an entry, my entire editor group gets the email notification that says "Your submission for [entry name] has been approved October 19, 2016 16:24 on [the website].".

Is this something you're aware of? I'm under a bit of time pressure so might have to pull it apart myself but thought I should let you know!

* * *

Workflow 0.9.3 on Craft CMS 2.6.2940

**Comment by loveevelyn** [comment]
This seemed to have been fixed in 0.9.4

>"[Fixed] Only individual editors receive approval/rejection email notifications - not each user in the editor group."

**Comment by JamesMcFall** [comment]
Thanks guys. I can confirm that after upgrading to 0.9.4 the issue is resolved :)

**Comment by engram-design** [comment]
@JamesMcFall, have you tried the latest version as @loveevelyn pointed out?

**Comment by JamesMcFall** [comment]
@engram-design Yes thanks Josh. I closed the issue.
