### ISSUE TITLE
Add reviewer notes to workflow overview table

### ISSUE THREAD

**Issue by charliestrafe** [engram-design/Workflow#155]
### Describe the bug

I have an issue where the reviewer notes that are added to workflow entries that are submitted for review do not show on the workflow overview table.

I have tried clicking the settings cog on the overview page, to add the reviewer notes to the table but there is no option to do so, unlike how there is for editor and publisher notes.

Please could the reviewer notes be added to the table as it would be really useful to see these when in the overview area.

### Steps to reproduce

1. Submit an item for review as an editor
2. Approve the item as a reviewer, add some reviewer notes as well
3. Go to the workflow overview table, there is no where to view these reviewer notes

### Craft CMS version

Craft Pro 4.1.4.1

### Plugin version

dev-craft-4 as 2.0.0-beta.4

### Multi-site?

No

### Additional context

No

**Comment by engram-design** [comment]
You can add "Editor Notes" and "Publisher Notes". There's not really a good way for us to consolidate multiple reviewers notes into the table format.
