### ISSUE TITLE
Approved & published workflow items title changes to [Deleted element] in workflow overview table

### ISSUE THREAD

**Issue by charliestrafe** [engram-design/Workflow#156]
### Describe the bug

I have an issue where my approved and published workflow entries titles are not being shown in the overview table. Instead, it says '[Deleted element]'. It should display the actual entry title once published. This may be due to the fact that in my revision of the entry, I changed just the title field and nothing else.

![Screenshot 2022-07-14 at 10 23 16](https://user-images.githubusercontent.com/47243887/178952269-3659248b-37d8-4bf3-960e-5cdeff06c6ea.png)

### Steps to reproduce

1. Submit an item for review (might need to change the entry title field)
2. Approve the review
3. Publish the element
4. Check the workflow overview table, the title will say '[Deleted element]'

### Craft CMS version

Craft Pro 4.1.4.1

### Plugin version

dev-craft-4 as 2.0.0-beta.4

### Multi-site?

No

**Comment by engram-design** [comment]
This is by design, for the moment. The reason being is that all submissions are made on a draft. Once the draft has been approved, the draft no longer exists. As such, it's been "deleted".

Even if we were to change this to show the title of the owner entry instead of the draft, that would be potentially misleading as the title could change from entry to draft and back again.

**Comment by charliestrafe** [comment]
I think the problem is our client is using workflow to keep a solid record of what has been approved, and who has approved it. But once it's been approved as the name now changes to 'Deleted element' it makes it very hard to my client to find out exact what entry was approved. I think your suggestion of changing it so the owner entry title instead would be good solution.

Alternatively, taking a stamp / record of the title as it is when the review is submitted would also work, and then next to it (if eligible) what the title is now. I've attached a screenshot mockup of this
![Screenshot 2022-07-14 at 12 27 40](https://user-images.githubusercontent.com/47243887/178972566-a731e8e3-4130-4cb2-a028-ef937cf52d11.png)

Thanks!

**Comment by engram-design** [comment]
Yep, agreed this probably needs even more of a proper look. For example, a submission element doesn't really "exist" from a users' point of view. If you click on a submissions title, you'll be taken off to the entry. I'd much rather see some content about the approval process, and the twists-and-turns it might've gone on in detail.

This should be fleshed out in more detail via https://github.com/verbb/workflow/issues/158

**Comment by charliestrafe** [comment]
Sounds great, is it likely this feature will be worked on soon? Just so I can feedback to my client. Thanks.

**Comment by engram-design** [comment]
In the next 1-2 months I'd say.

**Comment by engram-design** [comment]
This has been improved in [2.0.0-beta.8](https://github.com/verbb/workflow/releases/tag/2.0.0-beta.8) now that we're saving the original canonical entry, which is switched back to once the draft has been applied (and therefore deleted).
