### ISSUE TITLE
Workflow for craft 4 release date?

### ISSUE THREAD

**Issue by johannesSolvr** [engram-design/Workflow#160]
### Question

@engram-design Hi, We are working on a project that uses Workflow in Craft 4, and today the beta isn't stable enough for production. When do you recon this plugin will be out of beta and production ready?

**Comment by engram-design** [comment]
No ETA sorry. Can you comment on why the beta isn't stable enough for production?

**Comment by johannesSolvr** [comment]
I'm using Beta 3 now, and it kind of works, except that it is impossible to delete submissions. Beta 4 does not work, doesn't list submissions at all. And I also tried the solution in another issue to add a commit directly, but then I wasn't able to accept submissions. So it does seem a bit unstable at the moment, and since it is a beta that is not uncommon. That's why I wondered when it wass planned released.

**Comment by engram-design** [comment]
Ah, just realised I've forgotten to push the latest fixes to a new version. If you wouldn't mind installing [2.0.0-beta.5](https://github.com/verbb/workflow/releases/tag/2.0.0-beta.5) there are a bunch of fixes there that should hopefully address things.

Please do add any issues you find and I'll get them sorted. I've just got some refactoring and new features to add for the 2.0 release, but that should be in the next month.

**Comment by johannesSolvr** [comment]
Hi, just installed Beta.5 but I'm not able to approve a submission.

I get "Element action params did not validate" message when i try to approve

**Comment by engram-design** [comment]
Are you approving as a publisher or a reviewer? Are you trying to approve a submission from the entry, or elsewhere?

**Comment by johannesSolvr** [comment]
It happens when I try to approve as a publisher, but only when I try to change the status directly in the list, I can publish from the submission itself

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/workflow` requirement in `composer.json` to:

```
"require": {
  "verbb/workflow": "dev-craft-4 as 2.0.0-beta.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by johannesSolvr** [comment]
Added this not, and it works now, thanks

**Comment by engram-design** [comment]
Finalised [2.0.0](https://github.com/verbb/workflow/releases/tag/2.0.0). Refer to [blog post](https://verbb.io/blog/workflow-2) and [upgrade docs](https://verbb.io/craft-plugins/workflow/docs/get-started/upgrading-from-v1).
