### ISSUE TITLE
Exception after "Publisher User Group" user "approves only" 

### ISSUE THREAD

**Issue by yingban** [engram-design/Workflow#164]
### Describe the bug

After submit via "Approve only" an exception is thrown with "Invalid element ID" and error 400.

From "vendor/craftcms/cms/src/controllers/ElementsController.php"
Line 1612:  throw new BadRequestHttpException($elementId ? "Invalid element ID: $elementId" : "Invalid element UUID: $elementUid");

It is working well with "Approve and Publish" button though.

### Steps to reproduce

1. login as editor (can only create drafts)
2. create draft from existing entry (e.g. from single section type)
3. submit draft for approval with "Save draft and submit for review" button
4. get entry reviewed by reviewers user
6. login as chief editor
7. try to approve with "Approve only" button

### Craft CMS version

4.3.0

### Plugin version

2.0.0-beta.7

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.8](https://github.com/verbb/workflow/releases/tag/2.0.0-beta.8)
