### ISSUE TITLE
Template not found: workflow/{id}

### ISSUE THREAD

**Issue by MoritzLost** [engram-design/Workflow#165]
### Describe the bug

I just tried the update to version `2.0.0-beta.8`. Every link on the submissions overview leads to a 404 page with the following error:

> Template not found: workflow/1196636

The last digit is the submission ID.

Is there maybe a route definition missing, or is the link generated incorrectly?

### Steps to reproduce

1. Click on any submission link from the _All Submissions_ link on the Workflow overview page.

### Craft CMS version

4.3.1

### Plugin version

2.0.0-beta.8

### Multi-site?

No

**Comment by engram-design** [comment]
Yep, sorry - I was a bit too pre-emptive with that one! I'm currently working on a new [detail page](https://github.com/verbb/workflow/issues/158) for the next release (next week), so that will error out for the moment - sorry!

**Comment by MoritzLost** [comment]
@engram-design That was the quickest reply I've ever seen to an issue 🥇 😄 

Looking forward to the new detail page!

**Comment by engram-design** [comment]
Fixed in [2.0.0](https://github.com/verbb/workflow/releases/tag/2.0.0). Refer to [blog post](https://verbb.io/blog/workflow-2) and [upgrade docs](https://verbb.io/craft-plugins/workflow/docs/get-started/upgrading-from-v1).

**Comment by MoritzLost** [comment]
@engram-design Awesome, this looks great, thanks for the update! We'll try out the new version soon, looking forward to it!
