### ISSUE TITLE
Changing the status on the submission details page doesn't work

### ISSUE THREAD

**Issue by MoritzLost** [engram-design/Workflow#168]
### Describe the bug

On the new submission details page, there's a _Status_ dropdown in the sidebar which allows you to change the status of the submission. However, changing this status and then saving the submission using the _Save_ button at the top doesn't do anything – after saving the submission, it shows the previous status again. Also, the confirmation pop-up says `Comment saved successfully.`, which is weird since there's no comment field visible on the submission page.

![workflow-status-change](https://user-images.githubusercontent.com/10146880/203735595-38afffeb-5c49-452e-b907-11d008e84262.png)

### Steps to reproduce

1. As an editor, submit a draft.
2. As a publisher, go to the submission details view, change the status from _Pending_ to _Approved_ using the dropdown in the sidebar, then save the entry.

### Craft CMS version

4.3.3

### Plugin version

2.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [2.0.2](https://github.com/verbb/workflow/releases/tag/2.0.2)

**Comment by MoritzLost** [comment]
@engram-design Just tried 2.0.2, works well, thanks for the quick resolution! 🚀
