### ISSUE TITLE
Workflow submissions listing shows unauthorized site submissions in multisite environment

### ISSUE THREAD

**Issue by parthi-me** [engram-design/Workflow#171]
### Describe the bug

In a multisite environment, when a Publisher group user has access to a specific site, workflow listing shows all the site submissions including the sites which the user doesn't have access. but upon clicking the record we get error messge. Can we display only the records associated with these users' authorized site entries? 

### Steps to reproduce

1. On a multisite environment, Crate a user with workflow publisher group access.
2. Give him edit access permission only to the particular site.
3. Go to workflow and check the listing which displays all the records including the sites the user doesn't have access.

### Craft CMS version

3.7.61

### Plugin version

1.7.4

### Multi-site?

Yes

**Comment by engram-design** [comment]
This would be due to lack of true multi-site support in Workflow 1 (for Craft 3), which has been added in Workflow 2 (for Craft 4). We're not looking to back-track that functionality to Workflow 1, sorry.
