### ISSUE TITLE
Missing step in docs for publisher setup

### ISSUE THREAD

**Issue by tom-bywild** [engram-design/Workflow#177]
### Describe the bug

When following the [guide for setting up user roles](https://verbb.io/craft-plugins/workflow/docs/feature-tour/setup) properly, the permission for publishers to access the Workflow overview is missing from the documentation.

The documentation currently only instructs to **enable the access to Workflow in the control panel**, but misses to also add permission to access the overview of Workflow.

The required setting is placed at the very bottom, which is quite counterintuitive from a UX perspective, but not sure this can actually be changed by the Plugin.

<img width="223" alt="Screenshot 2022-12-15 at 10 35 52" src="https://user-images.githubusercontent.com/102795185/207825166-27f618a8-dc6d-44be-bb9f-7b41f7c4ce24.png">

### Steps to reproduce

1. Go to the [guide for setting up user roles](https://verbb.io/craft-plugins/workflow/docs/feature-tour/setup)
2. Follow steps
3. Sign-In as publisher
4. Try to open workflow page to see error

### Craft CMS version

Craft Pro 4.3.5

### Plugin version

2.0.2

### Multi-site?

No

**Comment by engram-design** [comment]
Sure, it's not _required_ that you have access to the Workflow plugin though. You can manage everything through the widget in the sidebar of an entry being reviewed, but I suppose there are links in the email that do point to the submission edit page now.

And yeah, the settings are alphabetical in user permissions - not much we can do about that.

Updated the docs.
