### ISSUE TITLE
editorNotes not saved from Front-end Submission when Entries saved as Drafts

### ISSUE THREAD

**Issue by romainpoirier** [engram-design/Workflow#178]
### Describe the bug

I have a Front-end Submission where users can edit Entries as Drafts (until approval):
```
{{ actionInput('elements/save-draft') }}
{{ hiddenInput('entryId', entry.id ?? null) }}
{{ hiddenInput('elementUid', entry.uid ?? null) }}
{{ hiddenInput('draftName', 'Test draft name') }}
{{ hiddenInput('workflow-action', 'save-submission') }}
{{ hiddenInput('editorNotes', 'Test editorNotes') }}
{{ hiddenInput('notes', 'Test notes') }}
```

This is working, but not the `editorNotes` described in the [doc](https://verbb.io/craft-plugins/workflow/docs/template-guides/front-end-submission#front-end-submission). Nothing is saved, neither on the Workflow submission, neither on the Draft. The only notes which is saved is the native `notes` (here filled with `Test notes`).

### Steps to reproduce

1. Submit a new Draft from front-end
2. Check the new Workflow submission and Draft

### Craft CMS version

4.3.5

### Plugin version

2.0.3

### Multi-site?

Yes

**Comment by engram-design** [comment]
Looks like the docs were out of date, this should be `workflowNotes` not `editorNotes`.
