### ISSUE TITLE
Issue with special characters in submission notes Craft CMS 3.x.x & Workflow 1.7.5

### ISSUE THREAD

**Issue by p1uymi** [engram-design/Workflow#190]
### Describe the bug

Issue with special characters in submission notes Craft CMS 3.x.x & Workflow 1.7.5

Sofar, we cann't upgrade the Craft CMS version to 4.x.x and are stuck on 3.x.x. Thus meaning we cann't update higher then Workflow 1.7.5. 

It seams, there is a issue with special characters in germen in the submission notes. e.g. "verl&amp;auml;ngert" should be "verlängert".

Is there any way there could be a fix for this for Craft 3.x.x? Or did you discontinue with Craft 3.x.x support?

<img width="143" alt="image" src="https://github.com/verbb/workflow/assets/18517228/ab60c744-27bb-4863-9d39-d114b8b27513">

### Steps to reproduce

1. Create Submission
2. Write verlängert in the notes
3. Review Note
4. Find "verl&amp;auml;ngert"

### Craft CMS version

Craft Pro 3.7.67

### Plugin version

11.7.5

### Multi-site?

yes

**Comment by engram-design** [comment]
I've backtracked this for the next release. To get this early, run `composer require verbb/workflow:"dev-craft-3 as 1.7.5"`.

**Comment by engram-design** [comment]
Fixed in [1.7.6](https://github.com/verbb/workflow/releases/tag/1.7.6)
