### ISSUE TITLE
"Editor Submission Notes Required" doesn't function

### ISSUE THREAD

**Issue by darylknight** [engram-design/Workflow#192]
### Describe the bug

Possibly a regression of #59

Our Editor group permissions look like this:

![image](https://github.com/verbb/workflow/assets/1250017/dd959758-7261-4d47-94f3-02cc74af5f11)

This means that in order to edit or submit anything, their first step is to Create a draft. Once they've done that, they can make changes, then submit for review. I've enabled the setting that requires submission notes here:

![image](https://github.com/verbb/workflow/assets/1250017/0db62fc8-df19-4570-97b7-25d28655971c)

However, when they make changes, it is not actually a required field, and they can submit their draft for approval without notes:

![image](https://github.com/verbb/workflow/assets/1250017/dc013771-5e10-46ed-a3c4-d5777679aa30)

### Steps to reproduce

1. Enable the lightswitch for "Editor Submission Notes Required"
2. Submit a draft for approval without adding any notes

### Craft CMS version

4.4.16.1

### Plugin version

2.0.5

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/workflow:"dev-craft-4 as 2.0.5"`.

**Comment by engram-design** [comment]
Fixed in [2.0.6](https://github.com/verbb/workflow/releases/tag/2.0.6)
