### ISSUE TITLE
Invalid draft ID after clicking reviewer email

### ISSUE THREAD

**Issue by leightonhughes** [engram-design/Workflow#194]
### Describe the bug

![Screen Shot 2023-10-24 at 12 37 06 pm](https://github.com/verbb/workflow/assets/5158786/2923a236-a3ab-476c-9768-4a2a3a9b1f43)

### Steps to reproduce

1. Author is submitting draft before creating entry.
2. URL in reviewer email has ?draftId=### at the end
3. Reviewer is clicking url and getting bad request screen
(Maybe I am overlooking something new in the Craft 4 entry workflow??)

### Craft CMS version

4.5.9

### Plugin version

2.0.5

### Multi-site?

No

### Additional context

Hey Josh, I‘ve tested this locally in a DDEV environment and getting this error. Let me know if you require anything else to debug. Hope you‘re doing well. :)
![CleanShot 2023-10-24 at 15 16 41@2x](https://github.com/verbb/workflow/assets/5158786/3198d8d2-f5e1-4aeb-8b8a-dc158744b98b)

**Comment by engram-design** [comment]
Wondering if you might've overwritten the default Workflow email message, and it doesn't reflect the latest changes? I can confirm a fresh install seems to be the correct link.

See the [default messages here](https://github.com/verbb/workflow/blob/c7845dfb17d4c436480f237aa15a6b96ddb16adc/src/translations/en/workflow.php#L8-L37), and just compare on your system.

Out of interest, what's the URL that the editor has when they've submitted the new entry? I assume it doesn't match the link in the email?

**Comment by leightonhughes** [comment]
The url no longer has draftID=### after its submitted as the entry seems to be created along with. Is there a setting somewhere that I need to configure so it doesn't get created?

**Comment by leightonhughes** [comment]
I just created a test editor and publisher and works fine.. 🤔

**Comment by leightonhughes** [comment]
@engram-design, figured out that it is because a user is assigned as an editor and publisher. Can you see if you can replicate please. :) Presume you've designed it in a way where it is not interchangeable with these roles. Would this be an easy add?

**Comment by engram-design** [comment]
Ah, I was wondering how it's possible the draft Is cleared on save, as it shouldn't be converting the draft entry to a non-draft one unless the user has permission to publish the entry.

That's a tricky one, but it should be an okay scenario as a publisher can't approve their own entries, despite being in the dual role. But you're right - the email link is incorrect in this case!

Fixed for the next release. To get this early, run `composer require verbb/workflow:"dev-craft-4 as 2.0.6"`.

**Comment by leightonhughes** [comment]
Thanks bud! Hey new Verbb site is looking great btw. Congrats on the 50th plugin too!

**Comment by engram-design** [comment]
Thanks buddy, good time for a refresh!
