### ISSUE TITLE
The status color not added to the entry listing page 

### ISSUE THREAD

**Issue by karthikkstar** [engram-design/Workflow#199]
### Describe the bug

The entry listing page does not display the status color. After upgrading from Craft 4.5.15 to 4.6.1,
Its worked on the craft (4.5.15).

https://github.com/craftcms/cms/issues/14156

### Expected behavior

![image](https://github.com/craftcms/cms/assets/85233749/c8b692ef-ae7b-44de-8575-70404ebfe46e)

### Actual behavior
![image](https://github.com/craftcms/cms/assets/85233749/2ad18a04-6d0e-4859-9c56-278643c00933)

### Steps to reproduce

1. After upgrading from Craft 4.5.15 to 4.6.1

### Craft CMS version

Craft Pro 4.6.1

### Plugin version

2.0.7

### Multi-site?

YEs

### Additional context

- Amazon S3 2.0.3
- AsyncQueue 3.1.1
- Blitz Recommendations 2.1.3
- Cloner 2.0.4
- Control Panel Body Classes 2.3.0
- Default Dashboard 2.0.1
- Device Detect 2.0.1
- Feed Me 5.3.0
- Fetch 2.0.0-beta.1
- Formie 2.1.2
- GeoMate 2.1.1
- Maps 4.0.4
- Myproperties 1.8.7
- Password Policy 4.1.0
- Redactor 3.0.4
- SEOmatic 4.0.37
- Site Switcher 2.3.0
- Social 3.0.0-beta.1
- Sprig 2.7.3
- Typed link field 2.1.5
- Workflow 2.0.7

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/workflow:"dev-craft-4 as 2.0.7"`.

**Comment by engram-design** [comment]
Fixed in [2.0.8](https://github.com/verbb/workflow/releases/tag/2.0.8)
