### ISSUE TITLE
Feature Request: Draft Manager / Viewer

### ISSUE THREAD

**Issue by mildlygeeky** [engram-design/Workflow#2]
Would be great if this had some sort of a view/list of any entries with drafts — right now there is no central place or visual indicator for content that is published and has a draft, and it feels like some sort of view of all entries with drafts might fit in with this plugin.

**Comment by engram-design** [comment]
Sounds great, I'll add it to the list!

**Comment by engram-design** [comment]
Added in [0.9.2](https://github.com/engram-design/Workflow/releases/tag/0.9.2)!

**Comment by mildlygeeky** [comment]
You're the best Josh! Trying it out today
