### ISSUE TITLE
Save button not working on submission edit page

### ISSUE THREAD

**Issue by karthikkstar** [engram-design/Workflow#201]
### Describe the bug

Hi Team,
admin/workflow/submissions/edit/1858845?site=uk
After clicking the "save" button on the submission edit page, an error occurs, displaying "Unable to find submission."

**Submissions Edit**
![image](https://github.com/verbb/workflow/assets/85233749/92ecce89-b10f-41fa-8f91-bffd26d28a9a)

**Error:**
![image](https://github.com/verbb/workflow/assets/85233749/a3a1aaf4-57eb-462a-992a-a0c1aa32566f)

Same-issue client report: https://github.com/verbb/workflow/issues/197

Thank you

### Steps to reproduce

1. Open the pending submission. and change the status to "approve." 
2. After clicking the "save" button on the submission edit page, an error occurs, displaying "Unable to find submission."

### Craft CMS version

Craft Pro 4.6.1

### Plugin version

dev-craft-4

### Multi-site?

yes

### Additional context

- Amazon S3	2.0.3
- AsyncQueue	3.1.1
- Blitz Recommendations	2.1.3
- Cloner	2.0.4
- Control Panel Body Classes	2.3.0
- Default Dashboard	2.0.1
- Device Detect	2.0.1
- Feed Me	5.3.0
- Fetch	2.0.0-beta.1
- Formie	2.1.2
- GeoMate	2.1.1
- Maps	4.0.4
- Myproperties	1.8.7
- Password Policy	4.1.0
- Redactor	3.0.4
- SEOmatic	4.0.37
- Site Switcher	2.3.0
- Social	3.0.0-beta.1
- Sprig	2.7.3
- Typed link field	2.1.5
- Workflow	dev-craft-4

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/workflow:"dev-craft-4 as 2.0.7"`.

**Comment by engram-design** [comment]
Fixed in [2.0.8](https://github.com/verbb/workflow/releases/tag/2.0.8)
