### ISSUE TITLE
Editor with normal editor permission cannot duplicate entries at all

### ISSUE THREAD

**Issue by azad6026** [engram-design/Workflow#205]
### Question

Is it possible to add a way to allow editors to be able to duplicate entries at all. Currently there is no way to do that for editors. Permission assigned to the editors are : Create new entries, View entries, View other users' drafts. So they can created drafts, but they cannot duplicate a page at all unless they have Save  entries permission which does not make sense since editors should not be able to save an entry.
Is this. a feature you would add any time or is it on Craft to give an extra permission value in user groups ?
Thanks for reading

### Additional context

Craft CMS 4.7.0
Workflow : 2.0.8

**Comment by engram-design** [comment]
I'd say this might be a Craft feature to add permissions for this, as I don't want Workflow to start creating custom user permissions and re-inventing the wheel with Craft's own permissions. I think this is a valid feature request to post with [Craft itself](https://github.com/craftcms/cms)

**Comment by azad6026** [comment]
Thanks for coming back to this. Perfect. Will look into that then. Cheers.
