### ISSUE TITLE
Memory Limit issue with 20k reviews

### ISSUE THREAD

**Issue by markhuot** [engram-design/Workflow#206]
### Describe the bug

Our site has 20k reviews stored in the DB and we're no longer able to fit all those reviews in memory. This is causing the `Reviews::_reviews()` method to fail because that's a lot of `Review` objects to retain. See: https://github.com/verbb/workflow/blob/ca22d896f012757064d45ab947ca42f63a33353d/src/services/Reviews.php#L186

This manifests itself in interesting ways. When trying to get `$submission->status` it makes calls to get the latest review which then loads all reviews in to memory.

Would it be possible to query the DB for specific reviews of a submission instead of trying to load them all?

I'm happy to PR this if you agree with the approach.

### Steps to reproduce

1. load 20k reviews in to the database
2. in a `php craft shell` session call `$submission->status`
3. the shell exists with a `memory_limit` error

### Craft CMS version

4.3.10

### Plugin version

2.0.4

### Multi-site?

No

### Additional context

I've verified the issue does not happen if I truncate my `craft_workflow_reviews` table. We'd rather not lose all that review history though if it can be avoided.

**Comment by engram-design** [comment]
Great call, I believe I just memoized everything for a lot of our plugins without giving it proper thought.

Should be fixed for the next release. To get this early, run `composer require verbb/workflow:"dev-craft-4 as 2.0.8"`.

**Comment by engram-design** [comment]
Updated in [2.0.9](https://github.com/verbb/workflow/releases/tag/2.0.9)
