### ISSUE TITLE
Cannot save submission - 3.0.0-beta.1

### ISSUE THREAD

**Issue by jlachancekffein** [engram-design/Workflow#209]
### Describe the bug

It's impossible to save a submission. Here's the error: `Undefined variable $request.`

The error is located on line 66 of the file `src/controllers/SubmissionsController.php`.

In my opinion, it should be replaced 

`$siteId = (int)$request->getParam('siteId'); `
with 
`$siteId = (int)$this->request->getParam('siteId');`

### Steps to reproduce

1. Create a submission
2. Save the submission

### Craft CMS version

5.1.2

### Plugin version

3.0.0-beta.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/workflow:"dev-craft-5 as 3.0.0-beta.1"`.

**Comment by engram-design** [comment]
Fixed in [3.0.1](https://github.com/verbb/workflow/releases/tag/3.0.1)
