### ISSUE TITLE
Submissions not visible to users with Workflow Overview permission

### ISSUE THREAD

**Issue by russback** [engram-design/Workflow#212]
### Describe the bug

User set as a publisher as per docs, with permission to view Workflow Overview, but user cannot access submissions section.

### Steps to reproduce

1. Set user with Workflow Overview permission.
2. Submit an entry for review.
3. Click on a link in the dashboard widget - shows 403.
4. Also no Workflow item on the sidebar and all access to /admin/workflow/ is denied.

### Craft CMS version

5.1.10

### Plugin version

3.0.0 Pro

### Multi-site?

Yes

**Comment by engram-design** [comment]
Can you confirm if they also have the "Access Workflow" permission under "General" enabled as well?

**Comment by russback** [comment]
Missed that. Now checked and links in the widget now work, but when clicking on Workflow in the breadcrumb, it's a 403.
So just a minor one.

Also noticed that all users with access to Workflow Overview can delete submission actions. Is that correct? They can also see the Status dropdown and Save button, although hitting Save doesn't save the change.

**Comment by engram-design** [comment]
I have just pushed a fix changes related to this for the next release. To get this early, run `composer require verbb/workflow:"dev-craft-5 as 3.0.0"`.

Which breadcrumb were you clicking on? It should all be to `admin/workflow`.

We probably want to introduce some more permissions here, but I'm concerned that's a breaking change now. But you're right, it doesn't _feel_ great not to have more fine-grained control over things. Typically, we'd been of the opinion publishers or admins should only have access to Workflow submissions.

As for saving submissions, you can only do that if you're not an editor. Changing the status does work, however you can't set something back to pending, and you can't approve your own submission.

**Comment by engram-design** [comment]
Fixed in [3.0.1](https://github.com/verbb/workflow/releases/tag/3.0.1)
