### ISSUE TITLE
Craft 3→4 migration TypeError on Submission & CP detail pages due to old “Reviewer” reviews having null data

### ISSUE THREAD

**Issue by AimeeHendrycks** [engram-design/Workflow#213]
### Describe the bug

I’m working on a Craft 3 → 4 upgrade.
My Workflow setup has an Editor group, 2 Reviewer groups, and a Publisher group.

I am running into a TypeError in two places:

1. Attempting to view an old (pre-Craft-4 upgrade) submission detail page.
![Screenshot 2024-07-12 at 10 52 51 AM](https://github.com/user-attachments/assets/9fdd978c-1717-40da-8498-3e1b1c243157)

2. Attempting to visit the entry detail page tied to the old submission with a Workflow user group applied.
![Screenshot 2024-07-12 at 11 02 26 AM](https://github.com/user-attachments/assets/2b91c3c1-1b17-4dd4-89b5-f57b37797fe1)

My test submission for this case has reviews for editor, one or both review groups, and publisher.

It appears that the culprit is that old “reviewer” reviews have a “data” value of null after the Craft 4 migration, causing the TypeErrors:

1. Submission detail page: https://github.com/verbb/workflow/blob/craft-4/src/services/Content.php#L39
2. Entry detail page: https://github.com/verbb/workflow/blob/craft-4/src/models/Review.php#L199

Screenshot of “craft_workflow_reviews” table w/ role=reviewer and data=null:
![Screenshot 2024-07-12 at 10 39 04 AM](https://github.com/user-attachments/assets/fbaf06e2-8e73-4dcf-b6db-ae427dcd680f)

My current fix would be to delete all old Craft 3 submissions before deploying the Craft 4 upgrade, but if we can account for the null data values on “reviewer” reviews, that’d be great!

P.S. I did not see any errors during the migration application process to Craft 4 - all migrations appeared to run well.

### Steps to reproduce

Upgrade to Craft 4 w/ submissions that have reviewer reviews and see that the data column is null for those reviews.

### Craft CMS version

3.9.13 → 4.8.10

### Plugin version

1.7.6 → 2.0.9

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/workflow:"dev-craft-4 as 2.0.9"`.

**Comment by AimeeHendrycks** [comment]
Thank you! The recent fix has addressed the error on the submission detail page, but I am still running into a TypeError on the CP entry detail page.

https://github.com/verbb/workflow/blob/craft-4/src/models/Review.php#L199

![image](https://github.com/user-attachments/assets/aeaff67f-0a70-4aec-8ee9-d2a8f6ab18da)

**Comment by engram-design** [comment]
Thanks! Just pushed a fix for that as well. To get this early, run `composer require verbb/workflow:"dev-craft-4 as 2.0.9"`.

**Comment by AimeeHendrycks** [comment]
Thanks for your work! I believe the TypeError I am encountering is for the first argument - `$oldReview->data` (rather than `$this->data`).

**Comment by engram-design** [comment]
My mistake, sorry. I've just normalized every instance of `getDiff()` now. To get this early, run `composer require verbb/workflow:"dev-craft-4 as 2.0.9"`.

**Comment by AimeeHendrycks** [comment]
This looks great - thank you!
