### ISSUE TITLE
Second Reviewer User Group not able to approve and reject a draft

### ISSUE THREAD

**Issue by yeboJoseph** [engram-design/Workflow#214]
### Describe the bug

1. Editor creates Draft 
2. First Reviewer User Group approves Draft
3. Second Reviewer User Group accesses draft edit page, but only sees the "Awaiting approval".
![workflow](https://github.com/user-attachments/assets/f3a682a8-2810-414e-879f-2da4a5cd3d8f)

Also, I would assume the publisher would get a notification to approve a draft after the second reviewer has submitted they're approval. Currently after the first reviewer as approved the draft, the publisher gets a notification to approve. 

### Steps to reproduce

1. Editor creates draft and submits for approval
2. First reviewer approves draft
3. Second reviewer goes to view entry and doesn't have the option to approve or reject

### Craft CMS version

4.10.7

### Plugin version

2.0.11

### Multi-site?

Yes

**Comment by engram-design** [comment]
Can you comment if there's any overlap between user groups for the users? I don't see that behaviour on my end (quick video below shows the process with 2 reviewer groups).

https://github.com/user-attachments/assets/57437d4f-7c7f-478f-bebe-023ca3551881

As for the email, I again can't replicate that. The only issue I see is that the editor currently gets notified when each reviewer approves their entry. They _probably_ shouldn't, as although it's been approved, the editor probably doesn't care if each reviewer approves their submission. They mostly care about the final publisher approval. Although maybe we just introduce another email for reviewer-approved.

**Comment by yeboJoseph** [comment]
Yup, there was an overlap between reviewer and editor. Thanks.
