### ISSUE TITLE
Email notifications are not configurable

### ISSUE THREAD

**Issue by elfacht** [engram-design/Workflow#215]
### Describe the bug

Setting up the plugin would set up the email notifications with variables only:

![Screen shot 2024-08-08 um 08 03 00](https://github.com/user-attachments/assets/df0f98d1-3087-4d47-9efd-fc2734bcb156)

After adding the templates like [described in the documentation](https://verbb.io/craft-plugins/workflow/docs/template-guides/email-notifications) the emails I receive will still only contain the variable names and not the actual content:

![Screen shot 2024-08-08 um 08 06 38](https://github.com/user-attachments/assets/94717129-c088-4869-abc1-1ea9fe94b07e)
![Screen shot 2024-08-08 um 08 07 24](https://github.com/user-attachments/assets/48f28927-e01d-46d9-8e05-e7e2af2ea6a6)

### Steps to reproduce

1. Install the plugin
2. Go to Utilities -> System messages
3. Edit the contents of the messages
4. Proceed to a workflow and receive an email notification.

### Craft CMS version

5.2.9

### Plugin version

3.0.1

### Multi-site?

No

### Additional context

I already did a clean install of the plugin to the environment because I thought there might be an error during installation, but it didn't help. And just in case this might be a translation issue:

![Screen shot 2024-08-08 um 08 17 51](https://github.com/user-attachments/assets/5569cff8-5b5c-43e6-a611-4594b7e7bb42)

**Comment by engram-design** [comment]
Should be fixed in [3.0.2](https://github.com/verbb/workflow/releases/tag/3.0.2), let me know if not?

**Comment by elfacht** [comment]
@engram-design Looks good so far, thanks!
