### ISSUE TITLE
Double submission required and to review when editing Matrix content

### ISSUE THREAD

**Issue by alexjcollins** [engram-design/Workflow#217]
### Describe the bug

From what I can deduce on the site I'm using Workflow on, there's an issue with having to submit an entry twice when editing content in a Matrix field. Here's a quick video example of the behaviour I'm describing: https://share.cleanshot.com/YrQ1Yr61

Entries when the edited field is not a matrix field function as expected.

Additionally, the reviewers get 2 notifications, and 2 entries appear in the list for approval.
![CleanShot 2024-08-20 at 08 56 07](https://github.com/user-attachments/assets/543c8c1e-5630-4edb-aa2d-394aff2470dd)

I guess this technically all makes sense if reviewing is happening at the Entry Type level, but in the case of a Matrix block, I think this could be confusing for reviewers.

### Steps to reproduce

1.  Edit content in a matrix field in a draft and submit for review

### Craft CMS version

5.2.10

### Plugin version

3.0.2

### Multi-site?

Yes

**Comment by engram-design** [comment]
This seems almost related to [this Neo issue](https://github.com/verbb/workflow/issues/216), I'll test this out. Thanks for the video!

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/workflow:"dev-craft-5 as 3.0.2"`.

**Comment by alexjcollins** [comment]
@engram-design Epic, thanks!

**Comment by engram-design** [comment]
Fixed in [3.0.3](https://github.com/verbb/workflow/releases/tag/3.0.3)
