### ISSUE TITLE
Unable to find the template “navigation/_svg/verbb-logo.svg” in "workflow/_layouts" at line 34.

### ISSUE THREAD

**Issue by Coysh** [engram-design/Workflow#25]
### Description
The plugin does not load on Craft 3:

craft\web\twig\TemplateLoaderException: Unable to find the template “navigation/_svg/verbb-logo.svg” in "workflow/_layouts" at line 34. in /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/TemplateLoader.php:122
### Additional info

- Plugin version: 1.0.0
- Craft version: 3.0.16.1

**Comment by engram-design** [comment]
Sorry about that, fixed in [1.0.1](https://github.com/verbb/workflow/releases/tag/1.0.1).
