### ISSUE TITLE
Missing component class

### ISSUE THREAD

**Issue by Coysh** [engram-design/Workflow#26]
### Description
When trying to load the main page - after setting Editor/Publisher groups in settings, I get a 'Missing component class error.'

`
craft\errors\MissingComponentException: Unable to find component class 'verbb\workflow\elements\submission'. in /home/forge/dev.eauk.org/vendor/craftcms/cms/src/helpers/Component.php:52
Stack trace:
#0 /home/forge/dev.eauk.org/vendor/craftcms/cms/src/services/Elements.php(155): craft\helpers\Component::createComponent(Array, 'craft\\base\\Elem...')
#1 /home/forge/dev.eauk.org/vendor/twig/twig/lib/Twig/Extension/Core.php(1619): craft\services\Elements->createElement(Array)
#2 /home/forge/dev.eauk.org/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\services\Elements), 'createElement', Array, 'method', false, false)`

### Steps to reproduce

1. Go to settings and add an editor/publisher group
2. Try and go to the workflow homepage

### Additional info

- Plugin version: 1.0.0
- Craft version: 3.0.16.1

**Comment by Coysh** [comment]
Update: Changing line 9 of 'templates/index.html' to `{% set elementType = 'verbb\\workflow\\elements\\Submission' %}` fixed this.

**Comment by engram-design** [comment]
Sorry about that, fixed in [1.0.1](https://github.com/verbb/workflow/releases/tag/1.0.1).
