### ISSUE TITLE
Plugin crashes due to folder path of verbb logo

### ISSUE THREAD

**Issue by mucoop** [engram-design/Workflow#27]
### Description
Installed the plugin in trial mode (e.g. "Try") and saw the following error when trying to access it from the left menu.

Twig Template Loading Error – craft\web\twig\TemplateLoaderException
/public_html/craft/vendor/verbb/workflow/src/templates/_layouts/index.html

> Unable to find the template “workflow/_svg/verbb-logo.svg” in "workflow/_layouts" at line 34.

### Steps to reproduce

1. install plugin from plugin store (i.e. using composer build)
2. try to access it from the left hand menu
3. get error above

### Additional info

- Plugin version:1.0.1
- Craft version:3

**Comment by engram-design** [comment]
Sorry about that, should be fixed in [1.0.2](https://github.com/verbb/workflow/releases/tag/1.0.2)
