### ISSUE TITLE
Can only submit for approval once / Blank metadata

### ISSUE THREAD

**Issue by theskyfloor** [engram-design/Workflow#3]
Currently it seems that an entry can only be submitted for approval once... is this the correct behavior as of right now?

Additionally the editor/publisher fields all seem to be blank on my test install.

Sorry if these are already known/planned issues.

Love it so far! Much needed.

![screen shot 2016-06-25 at 12 18 26 pm](https://cloud.githubusercontent.com/assets/8887839/16358093/f19cbe8a-3ace-11e6-9661-899828cd29c1.png)
![screen shot 2016-06-25 at 12 18 20 pm](https://cloud.githubusercontent.com/assets/8887839/16358094/f1ac4684-3ace-11e6-8463-a8f085d16524.png)

**Comment by theskyfloor** [comment]
Also it appears date approved is the same on every entry thus far... not sure what is up there but it is impossible I created and approved those entries separated by several minutes.

**Comment by engram-design** [comment]
@theskyfloor Thanks for the feedback! Sorry about the issue with date approved, thats an issue. I've also modified the user object, as I think your above screenshot shows a user without a name value.

What do you mean the fields are blank?

And yeah, I'm just working through how to handle drafts. When its a un-published entry (disabled), its okay, but once enabled, the editor has to create a new draft. Just working through that!

**Comment by engram-design** [comment]
@theskyfloor Just added this in for you, works well with Drafts now. Next thing on the todo list is to tie submissions to entry versions.

By the way - you'll need to uninstall and install the plugin again as I've made some database changes. I'm not going to implement migrations until after 1.0 (which will be very soon after initial feedback).
