### ISSUE TITLE
Add greater flexibility around Editors/Publishers

### ISSUE THREAD

**Issue by engram-design** [engram-design/Workflow#34]
Such as, having both as the same user, selecting specific recipients.

Also adding notes to editor.

**Comment by RobErskine** [comment]
Hey Josh. Loving this plugin, thanks for all the work on it. 

Just wanted to piggyback on this ticket for a feature request/enhancement. It would be great to have more control with user groups outside of editors and publishers. It would be great to create custom roles and have content filter through a funnel, such as:

Editor -> Proofreader -> Editor 
or more complex:
Copywriter -> Designer -> Proofreader -> Merchant -> Publisher

Thanks again,
Rob

**Comment by saschapi** [comment]
And one more piggyback: 

Having the option to have different Groups as Editor and Publisher for different Entry types would be a big advantage. Currently this will stop us from using it.

**Comment by Alxmerino** [comment]
Yes, I would also love to piggyback on this as well!

**Comment by engram-design** [comment]
@RobErskine This has been added in [1.5.0](https://github.com/verbb/workflow/releases/tag/1.5.0) in the form of [Reviewers](https://verbb.io/craft-plugins/workflow/docs/feature-tour/reviews).

@saschapi @Alxmerino I'm opening a separate issue for your FR, as this one is a bit vague or just `greater flexibility` - see https://github.com/verbb/workflow/issues/114
