### ISSUE TITLE
Emails only showing placeholder text

### ISSUE THREAD

**Issue by phoob** [engram-design/Workflow#38]
### Description
When the plugin sends emails to either publishers or editors, the email only shows placeholder text. 

![image](https://user-images.githubusercontent.com/1475800/50686724-cb74bf00-101e-11e9-8d26-0529ead1e81e.png)

### Steps to reproduce

1. Log in as publisher and create a submission OR log in as editor and approve/refuse submission
2. See email sent to editor OR publisher

### Additional info

- Plugin version: 1.0.3
- Craft version: 3.0.36

**Comment by phoob** [comment]
Hello again! Tested some more. It seems this error only occurs when cp language is set to something other than english..

**Comment by phoob** [comment]
For now I just copied the language directory from en -> nb (norwegian).. that solved the problem temporarily..

**Comment by engram-design** [comment]
Struggling the reproduce this one actually, and I have tested with the CP language set to a non-english language for both editor and publisher. I'll do some more testing however...

I've even tested changing my base site's language just to be sure. Have you edited the email message through the control panel at all?

**Comment by phoob** [comment]
This was before 3.1... was not aware that was possible before..!? So have not tried editing the messages in CP

**Comment by engram-design** [comment]
Yep, its always been possible to edit the messages in the CP, but sounds like that's not the issue. First step is to try and reproduce this! I'll keep at it...

**Comment by engram-design** [comment]
Closing this for the moment, as I've tried all sorts of ways to reproduce this. Please let me know if its still an issue, and I'd suggest we try and get in touch over Discord (handle `crawf`)
