### ISSUE TITLE
Feature Request: Deny/hold entry

### ISSUE THREAD

**Issue by bartrylant** [engram-design/Workflow#4]
It would be cool if there was a button to deny the publish request. Even better would be if there was a field where a publisher can enter why the entry was denied. On clicking the "deny" button, the editor would receive an email with the message that his entry was denied + the reason (filled in by the publisher) + a direct link to re-edit the entry.

**Comment by engram-design** [comment]
Yep, a great idea. I'll be integrating more of the core Notes functionality which keeps things native. Watch out for it!

**Comment by engram-design** [comment]
This has now been implemented in [0.9.3](https://github.com/engram-design/Workflow/releases/tag/0.9.3).
