### ISSUE TITLE
Feature request: Notes about your submission

### ISSUE THREAD

**Issue by phoob** [engram-design/Workflow#40]
It would be very nice to have the option for publishers to add notes to their submissions, as messages to the editors. 

The draft notes could be used here, but doesn't serve the same purpose. Also the draft notes are not very easy to find/use.

**Comment by siffring** [comment]
+1 for this. Our client is a government agency that wants the ability for an approver to know what changed before approving. Otherwise, I'm not sure how they'd know without visually comparing each field with the existing page.

**Comment by engram-design** [comment]
Not quite sure what you mean here - Publishers (the ones who approve an editors submission to go live) have a section where they can add comments, that get sent back to the editor if they approve or reject a submission (so they can act on it).

I don't suppose you mean to add this to editors when they submit? If so, happy to add that in.

**Comment by phoob** [comment]
Yes, that’s exactly what I mean @engram-design :)

**Comment by engram-design** [comment]
Added in [1.1.0](https://github.com/verbb/workflow/releases/tag/1.1.0)

**Comment by alexrubin** [comment]
@engram-design this is super helpful. 

Any chance you would consider adding an optional "required" setting for the new field for editors?

**Comment by engram-design** [comment]
Added in [1.1.2](https://github.com/verbb/workflow/releases/tag/1.1.2) @alexrubin.
