### ISSUE TITLE
Users can't access entries due to php error

### ISSUE THREAD

**Issue by matt-adigital** [engram-design/Workflow#41]
### Description
When no sections are enabled at all but the plugin is installed, members in the selected groups see a yii\base\ErrorException where in_array() expects parameter 2 to be array, string given. This is in workflow/src/services/Service.php on line 63. In this case enabledSections is not equal to '*', but neither is it an array as nothing has been selected, thus it throws an error.

### Steps to reproduce

1. Login as User
2. Click into an entry

### Additional info

- Plugin version: 1.0.3
- Craft version: 3.0.37

**Comment by engram-design** [comment]
Should be fixed in [1.1.0](https://github.com/verbb/workflow/releases/tag/1.1.0)
