### ISSUE TITLE
500 when POST actions/element-indexes/get-elements

### ISSUE THREAD

**Issue by mattrothenberg** [engram-design/Workflow#42]
### Description
When visiting the `Overview` tab, I get a `500` error from the following endpoint and see the following toasts.

`index.php?p=admin/actions/element-indexes/get-elements`

![screen shot 2019-01-16 at 6 57 25 pm](https://user-images.githubusercontent.com/5148596/51286349-9eca8b00-19c0-11e9-8e52-d55029cba4e9.png)

### Steps to reproduce

2. Click Workflow from menu
3. See errors

### Additional info
- Plugin version: `1.0.3`
- Craft version: Craft Pro 3.10

**Comment by engram-design** [comment]
Are you able to use the network tools (in Developer tools in Chrome) to see what the response is for this failed ajax request? Can't reproduce this locally, so flying blind otherwise.

**Comment by mattrothenberg** [comment]
This seems to have disappeared after downgrading Craft to 3.0.37.

Sorry for the false alarm.

**Comment by engram-design** [comment]
Should be fixed in [1.1.0](https://github.com/verbb/workflow/releases/tag/1.1.0)
