### ISSUE TITLE
editorNotes Column Not Found Error on Drafts Tab

### ISSUE THREAD

**Issue by mattrothenberg** [engram-design/Workflow#48]
### Description
Just bumped Workflow from `1.0.3` to `1.1.0`. Installation seems to have gone OK on both development and prod, but I'm getting the same error in both environments.

<img width="1384" alt="screen shot 2019-02-25 at 8 52 25 am" src="https://user-images.githubusercontent.com/5148596/53341973-eb1bbb80-38da-11e9-8ddc-8d57fd6040da.png">

### Steps to reproduce

1. Bump versions
2. `composer update`
3. Visit admin panel, update the DB through the on-screen UI
4. Click the **Drafts** tab through the Workflow UI
5. Error

### Additional info

There don't seem to be any pending migrations (e.g., `./craft migrate/all` doesn't tell us anything).

- Plugin version: 1.1.0
- Craft version: Latest

**Comment by engram-design** [comment]
Should be fixed in [1.1.1](https://github.com/verbb/workflow/releases/tag/1.1.1)

**Comment by mattrothenberg** [comment]
@engram-design ❤️
