### ISSUE TITLE
Error clicking a user name

### ISSUE THREAD

**Issue by ghost** [engram-design/Workflow#50]
### Description

As an editor user without any user permissions, a click on a user name in the submission notes results in an error. Maybe you can make the name then only text and not a link?

### Steps to reproduce

This is true for any user name in any submission note seen in the right sidebar. 

### Additional info

- Plugin version: 1.1.1
- Craft version: 3.1.14

**Comment by engram-design** [comment]
Updated in [1.1.2](https://github.com/verbb/workflow/releases/tag/1.1.2)

**Comment by ghost** [comment]
Almost right! When I assign the "Edit users" permission to my publisher's user group, I do not get a normal name anymore, but this:

```<a href='http://craft3.test/admin/users/49'>Publisher One</a> ```

I see the HTML inside the submission notes.

**Comment by engram-design** [comment]
Whoops, right you are! Fixed in [1.1.3](https://github.com/verbb/workflow/releases/tag/1.1.3)

**Comment by ghost** [comment]
Works! I can see the linked name as before when I have permission and only the name when not! 👍
