### ISSUE TITLE
Publishers have access to settings - 403 error when saved

### ISSUE THREAD

**Issue by alexrubin** [engram-design/Workflow#55]
### Description
Might I suggested adding a granular permission to Workflow OR utilizing the same IsAdmin functionality to determine whether or not the "Settings" tab is displayed. This would avoid the error shown below.

### Steps to reproduce

1. Login to CP as a Publisher
2. Visit Settings tab
3. Save settings (403 Forbidden returned)

<img width="1029" alt="screenshot 2019-03-05 13 50 44" src="https://user-images.githubusercontent.com/20839/53829581-7128a980-3f4e-11e9-884f-da9763da212a.png">

### Additional info

- Plugin version: 1.1.5
- Craft version: 3.1.15

**Comment by engram-design** [comment]
Added/improved in [1.1.6](https://github.com/verbb/workflow/releases/tag/1.1.6)
