### ISSUE TITLE
Error sending editor email notifications

### ISSUE THREAD

**Issue by mark-adigital** [engram-design/Workflow#57]
Hi,

Editor email notifications aren't sending for me, and I've found this related error in the Workflow log:

> 2019-03-11 06:00:53 [-][27][-][info][workflow] Failed to send editor notification to mark@adigital.co.uk - Calling unknown method: verbb\workflow\elements\Submission::notes() in "__string_template__a0cb3a36dc1b26507a194b1a311a3e97369751a9e710c6a23091ca95a3f511e3" at line 16

This is running Craft Pro 3.1.17.1 and Workflow 1.1.7.

Thanks,

Mark

**Comment by mark-adigital** [comment]
Ah - resolved this, the notes are now split into `editorNotes` and `publisherNotes`, could just be worth updating the docs here to reflect that: https://verbb.io/craft-plugins/workflow/docs/developers/submission

**Comment by engram-design** [comment]
Whoops, I thought I had updated all these references. Done!

**Comment by knynkwl** [comment]
I am getting a similar error. The publishers get emails fine, but once it's approved, the editor doesn't receive an email.

`Failed to send editor notification to email@gmail.com - in_array() expects parameter 2 to be array, string given`

Craft 3.1.33
Workflow 1.1.12

**Comment by knynkwl** [comment]
@engram-design any idea what's happening here?

**Comment by engram-design** [comment]
Should be fixed in [1.2.2](https://github.com/verbb/workflow/releases/tag/1.2.2).
