### ISSUE TITLE
Additional email options

### ISSUE THREAD

**Issue by mark-adigital** [engram-design/Workflow#58]
Hi,

Just passing on a couple of feature requests from a client, might it be possible to add settings so that the editor notification emails can include a CC to the publisher whose action triggered them and to make that publisher's email address the reply-to address of the email for the editor's convenience?

Thanks,

Mark

**Comment by engram-design** [comment]
Happy to look at adding more settings. I've also added [some events](https://verbb.io/craft-plugins/workflow/docs/developers/events#the-beforeSendEditorEmail-event) so you can directly modify the email options before they're sent.

I've added those options to the plugin as well.

See [1.1.8](https://github.com/verbb/workflow/releases/tag/1.1.8)

**Comment by mark-adigital** [comment]
That's great - thank you!
