### ISSUE TITLE
Matrix fields

### ISSUE THREAD

**Issue by proximo7** [engram-design/Workflow#61]
### Description
Changes to matrix fields don't appear to save. I can change rich text, titles, etc but matrix fields do not appear to save their content when on an editor account. 

### Steps to reproduce

1. Made changes to a matrix field in Editor account. 
2. Entry saves as draft but changes vanish. Publisher view of draft does not show the change either. Works normally for titles, rich text, etc though.

### Additional info

- Plugin version: 1.1.9 
- Craft version: 3.1.21.1

**Comment by engram-design** [comment]
That seems strange behaviour, and I'm not able to immediately replicate it. Just so I'm clear, as an editor, you create a new entry, add some Matrix content, then hit "Save and submit for review"? After that point when the page refreshes your changes to the Matrix field are gone?

**Comment by proximo7** [comment]
This turned out the be a bug with Craft - which they fixed. Turned out that drafts didn’t save matrix data properly. Had nothing to do with Workflow.

**Comment by engram-design** [comment]
Ah, good to know!
