### ISSUE TITLE
Seeing Additional Tabs in User Edit Screen

### ISSUE THREAD

**Issue by rogertinch** [engram-design/Workflow#63]
### Description
I adjusted permissions for a Publisher User Group and am now seeing non-User tabs and fields in the User edit screen.

![image](https://user-images.githubusercontent.com/11000310/57662371-de8f3100-75b4-11e9-8a0f-ca0230304f0b.png)

### Steps to reproduce

1. Create 2 different user groups
2. Create 2 different sets of permissions for the user groups
3. Assign some users to one user group and the rest on the other user group
4. Go into a User to edit which User Group they're part of and you see non-User tabs showing up in the UI

### Additional info

- Plugin version: 1.1.9
- Craft version: Craft CMS 3.2.0-alpha.5

**Comment by engram-design** [comment]
Is this still occurring? I haven't really been able to replicate it...

**Comment by rogertinch** [comment]
Nope and it was unrelated to this plugin.
