### ISSUE TITLE
Workflow completely breaks on Craft 3.2.0-alpha.6.2

### ISSUE THREAD

**Issue by rogertinch** [engram-design/Workflow#66]
### Description

A bunch of changes were made to how Craft handles drafts and revisions in 3.2. If you have the Workflow plugin installed it breaks the entire site. Here's the [gist of the stack trace](https://gist.github.com/tinchalamo/482c8f52beddfffcc63fa04defa3d46c).

### Steps to reproduce

1. Install Craft 3.2.0-alpha.6.2
2. Install Workflow plugin
3. Run project config sync

### Additional info

- Plugin version: 1.1.9
- Craft version: 3.2.0-alpha.6.2

**Comment by engram-design** [comment]
We haven't tested it at all on 3.2.0-alpha, and as you mention drafts and versions have been significantly refactored. We'll provide an update in the next few weeks before a formal release of 3.2.

**Comment by rogertinch** [comment]
Brad Bell has this to say FYI:

Ahh, looks like the Workflow plugin is referencing a class that got removed in the latest 3.2 release. Will go ahead and add it back in but deprecate it so that won't bomb if the plugin is installed for the next 3.2 release.

**Comment by engram-design** [comment]
Should be fixed in [1.2.0-beta.1](https://github.com/verbb/workflow/releases/tag/1.2.0-beta.1)
