### ISSUE TITLE
Multi-site / multi-language validation error

### ISSUE THREAD

**Issue by bitsfabrikvienna** [engram-design/Workflow#70]
### Description

On a multi-site setup with different languages a "**Couldn’t propagate element to other site due to validation errors**" exception occurs if the workflow editor wants to submit an entry for review that includes a **required** translatable field that is empty in one language.

I guess it should not be possible to submit for review something with validation errors in the other language/site

### Steps to reproduce

1. create a multi-site with 2 languages
2. create a section with an entry type with a required text field, that is defined as "translate for each language"
3. the editor fills in text in one language and removes this text in the other language
4. editor clicks on submit for review
5. craft cms throws _Couldn’t propagate element to other site due to validation errors_ 

### Additional info

- Plugin version: 1.1.10
- Craft version: 3.1.30

**Comment by engram-design** [comment]
Fixed in [1.1.11](https://github.com/verbb/workflow/releases/tag/1.1.11)
