### ISSUE TITLE
Can't list pending workflows...

### ISSUE THREAD

**Issue by effer89** [engram-design/Workflow#72]
### Description
Gives me an error when trying to  show workflows...
And show this message when request is made to: **/index.php?p=admin/actions/element-indexes/get-elements**
`error: "An exception has been thrown during the rendering of a template ("Getting unknown property: verbb\workflow\elements\Submission::name")."`

Please fix this flow definitively I use it heavily :)

### Steps to reproduce

1. Click on "Workflow" menu or open /admin/workflow

### Additional info

- Plugin version: 1.1.11
- Craft version: Craft Pro 3.1.32.1

**Comment by engram-design** [comment]
Should be fixed in [1.1.12](https://github.com/verbb/workflow/releases/tag/1.1.12)

**Comment by effer89** [comment]
Works like a charm! Thank you!! :D
