### ISSUE TITLE
Not compatible with Craft 3.2

### ISSUE THREAD

**Issue by boxadesign** [engram-design/Workflow#73]
### Description

The plugin does not work with Craft 3.2

### Steps to reproduce

1. 
2.

### Additional info

- Plugin version: Latest
- Craft version: 3.2

**Comment by engram-design** [comment]
There is a beta version with compatibility via https://github.com/verbb/workflow/releases/tag/1.2.0-beta.1, and will release shortly.

You can also install via `composer require verbb/workflow:1.2.0-beta.1`

**Comment by boxadesign** [comment]
Hi @engram-design I still get the same error when opening the workflow page

![Screenshot 2019-07-11 at 11 22 25](https://user-images.githubusercontent.com/1015442/61043455-3b00a800-a3ce-11e9-8bde-4ab969701cdb.png)

**Comment by engram-design** [comment]
@boxadesign What's the error shown in the web console? If you can, find the error in the Network tab (in Chrome), find which request is marked in red, and have a look at the preview tab?

**Comment by boxadesign** [comment]
![image](https://user-images.githubusercontent.com/1015442/61043687-c8dc9300-a3ce-11e9-83e3-28fb0f5ec596.png)

**Comment by boxadesign** [comment]
`error: "An exception has been thrown during the rendering of a template ("Getting unknown property: verbb\workflow\elements\Submission::name")."`

**Comment by engram-design** [comment]
Can you try [1.2.0](https://github.com/verbb/workflow/releases/tag/1.2.0)?

**Comment by boxadesign** [comment]
@engram-design Seems good now. I'll let you know if there are any other issues. Thanks.

**Comment by boxadesign** [comment]
@engram-design Another error when trying to save and submit for review:

![image](https://user-images.githubusercontent.com/1015442/61054726-f255e880-a3e7-11e9-826a-15dad3bc58d0.png)

There seems to be an issue with the autosave and not sure if it's related to this plugin. Drafts don't seem to be autosaved and unless saved manually, disappear.

**Comment by boxadesign** [comment]
![image](https://user-images.githubusercontent.com/1015442/61056031-993b8400-a3ea-11e9-83f0-74932ee5067f.png)

**Comment by jasonmccallister** [comment]
Getting the same, sent some details to the support from on the website.

**Comment by engram-design** [comment]
@boxadesign Can you provide the steps for this issue? Is this a new entry, or an existing entry trying to submit?

**Comment by boxadesign** [comment]
@engram-design I've actually had to revert back to Craft 3.1 but I think the issue is to do with a bug in the new autosave. Essentially an entry would not be saved at all unless it was published. The fix is goin into the next release and is available under a beta release.

A new entry created by an editor, submits for review, gets error.

**Comment by engram-design** [comment]
@boxadesign thanks for the feedback, just wasn't able to reproduce it on my end. @jasonmccallister let me know if you're available to confirm?

**Comment by watarutmnh** [comment]
Hi, I have an error when try to install the plugin with Craft CMS 3.2.1.

![screenshot](https://user-images.githubusercontent.com/6081378/61169329-ef4d2a80-a596-11e9-8f6e-a8d1077b2ff2.png)

**Comment by engram-design** [comment]
@watarutmnh Can you look at your storage/logs/web.log file for information on the error? I believe that's a slightly different issue than what the original issue was.

**Comment by engram-design** [comment]
Please see [1.2.1](https://github.com/verbb/workflow/releases/tag/1.2.1) for the latest fixes.

**Comment by watarutmnh** [comment]
@engram-design 
I moved my case to #74
