### ISSUE TITLE
Rejected submission still appears in pending list

### ISSUE THREAD

**Issue by effer89** [engram-design/Workflow#78]
### Description
Rejected submission still appears in pending list

### Steps to reproduce

1. Reject an submission
2. Go to Workflow -> Overview -> Sort By "Pending"

### Additional info

- Plugin version: 1.2.1
- Craft version: Craft Pro 3.2.5.1

**Comment by engram-design** [comment]
Should be fixed in [1.2.2](https://github.com/verbb/workflow/releases/tag/1.2.2).
