### ISSUE TITLE
Error Approving Submission

### ISSUE THREAD

**Issue by jujubh** [engram-design/Workflow#79]
### Description
Error received on approval.

No submission with the ID “751” - etc

### Steps to reproduce

1. Approve any submission

### Additional info

- Plugin version: 1.2.2
- Craft version: Craft Pro 3.2.9

Exception: No submission with the ID “751” in /var/www/vendor/verbb/workflow/src/controllers/SubmissionsController.php:189
Stack trace:
#0 /var/www/vendor/verbb/workflow/src/controllers/SubmissionsController.php(110): verbb\workflow\controllers\SubmissionsController->_setSubmissionFromPost()
#1 [internal function]: verbb\workflow\controllers\SubmissionsController->actionApproveSubmission(NULL, Object(craft\elements\Entry))
#2 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('approve-submiss...', Array)
#5 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('approve-submiss...', Array)
#6 /var/www/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('workflow/submis...', Array)
#7 /var/www/vendor/verbb/workflow/src/services/Service.php(120): craft\web\Application->runAction('workflow/submis...', Array)
#8 [internal function]: verbb\workflow\services\Service->onAfterApplyDraft(Object(craft\events\DraftEvent))
#9 /var/www/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\DraftEvent))
#10 /var/www/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterApplyDraft', Object(craft\events\DraftEvent))
#11 /var/www/vendor/craftcms/cms/src/services/Drafts.php(270): yii\base\Component->trigger('afterApplyDraft', Object(craft\events\DraftEvent))
#12 /var/www/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(385): craft\services\Drafts->applyDraft(Object(craft\elements\Entry))
#13 [internal function]: craft\controllers\EntryRevisionsController->actionPublishDraft()
#14 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('publish-draft', Array)
#17 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('publish-draft', Array)
#18 /var/www/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entry-revisions...', Array)
#19 /var/www/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('entry-revisions...', Array)
#20 /var/www/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#21 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /var/www/web/index.php(28): yii\base\Application->run()
#23 {main}

**Comment by engram-design** [comment]
Out of interest, is this a new install of Workflow, or was this installed on a previous version and updated?

**Comment by jujubh** [comment]
It's a new install of Workflow, we initially installed on to Craft 3.2.8, experienced the error and then upgraded to Craft 3.2.9 to see if it resolved the issue.

**Comment by engram-design** [comment]
Gotcha, I believe this is a bug for new installs, which is why I asked. Will have that fixed up shortly.

**Comment by jujubh** [comment]
Excellent, thanks.

**Comment by jasonmccallister** [comment]
Having the same thing, thank you!

**Comment by ghost** [comment]
When do you expect to have a release with this bugfix? Not to add urgency, just trying to decide whether or not I want to wait with a deploy. Thanks!

**Comment by engram-design** [comment]
@renzo-s Added in https://github.com/verbb/workflow/releases/tag/1.2.2.1
