### ISSUE TITLE
Error Saving New Entry

### ISSUE THREAD

**Issue by jujubh** [engram-design/Workflow#80]
### Description

On saving new entry using "Save draft and submit for review" button an error occurs.

HTTP 404 – Not Found – yii\web\NotFoundHttpException
Entry not found

### Steps to reproduce

1. Create new entry
2. Save using "Save draft and submit for review"

### Additional info

- Plugin version: 1.2.2
- Craft version: Craft Pro 3.2.9

yii\web\NotFoundHttpException: Entry not found in /var/www/vendor/craftcms/cms/src/controllers/EntriesController.php:588
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/controllers/EntriesController.php(81): craft\controllers\EntriesController->_prepEditEntryVariables(Array)
#1 [internal function]: craft\controllers\EntriesController->actionEditEntry('topics', 762, NULL, NULL, NULL, NULL)
#2 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('edit-entry', Array)
#5 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#6 /var/www/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entries/edit-en...', Array)
#7 /var/www/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#8 /var/www/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /var/www/web/index.php(28): yii\base\Application->run()
#11 {main}

**Comment by engram-design** [comment]
Does the entry actually get submitted for review?

**Comment by jujubh** [comment]
It does get submitted for review but the entry is not saved.

**Comment by mattrothenberg** [comment]
Can confirm this issue as well, in addition to https://github.com/verbb/workflow/issues/77

## Additional info
- Plugin version: 1.2.2
- Craft version: Craft Pro 3.2.9

**Comment by knynkwl** [comment]
+1

**Comment by engram-design** [comment]
Should be fixed in [1.2.3](https://github.com/verbb/workflow/releases/tag/1.2.3). Thanks @mattrothenberg for your time with this issue!
