### ISSUE TITLE
Missing Entry Titles on Drafts list

### ISSUE THREAD

**Issue by knynkwl** [engram-design/Workflow#82]
### Description
We have a bunch of missing entry titles on our Draft list.

Is this due to deleting a draft?

### Additional info

- Plugin version: 1.2.2
- Craft version: 3.2.9

<img width="1035" alt="Screen Shot 2019-08-15 at 9 22 48 AM" src="https://user-images.githubusercontent.com/4225771/63097674-15bc0800-bf3f-11e9-952d-19844376b678.png">

**Comment by engram-design** [comment]
I would say these are entries that don't have a title yet, I'll have that fixed up shortly
