### ISSUE TITLE
Delete Draft Entries if they were deleted or not saved.

### ISSUE THREAD

**Issue by knynkwl** [engram-design/Workflow#83]
### Description
When creating an entry, if the user never saves it (i.e. enters some content, then switches pages), or deletes an entry, the entry draft still appears in the draft list.

Ideally it would delete the entry from the list if there is no entry. Click on these items gives a `Entry not found` page.

### Steps to reproduce

1. add an entry
2. don't save it, or delete it
3. go to drafts
4. click on the null entry draft

### Additional info

- Plugin version: 1.2.3
- Craft version:  3.2.10

**Comment by engram-design** [comment]
@knynkwl I'm actually removing the Drafts screen altogether now as its now included in Craft core. In previous version of Craft, it was pretty tedious to see all draft entries, as you'd have to go into each specific entry and look at the version/site dropdown.

Now - you can go to any section, and change the status dropdown from Live to Drafts. As such, this screen is being deprecated (removed) in [1.3.0](https://github.com/verbb/workflow/releases/tag/1.3.0)
