### ISSUE TITLE
Feature Request: Approve (but don't publish) Entry button

### ISSUE THREAD

**Issue by bliswebagency** [engram-design/Workflow#84]
## Steps to reproduce

1. An Editor edits an Entry which is Disabled. They submit it for Review.
2. A Publisher reviews and Approves it.
3. The Status is then automatically changed from "Disabled" to "Enabled".

### Additional info

The scenario above results in some entries going live before intended.

If possible, it would be great to be able to "Approve" an entry without Publishing it (i.e. having the Status automatically change).

**Comment by engram-design** [comment]
Added in [1.3.0](https://github.com/verbb/workflow/releases/tag/1.3.0)
