### ISSUE TITLE
Draft entries with deleted section are still being pulled and throw some error

### ISSUE THREAD

**Issue by willard** [engram-design/Workflow#90]
### Description

when accessing the url /admin/workflow/drafts, it's throw some error, where section id is missing.

i think, draft entries with deleted section are still being pulled by this code :

// BaseController.php
`$drafts = Entry::find()->drafts(true)->all();

  return $this->renderTemplate('workflow/drafts', [
      'entries' => $drafts,
 ]);`

// template/drafts.html
and on template, entry.getCpEditUrl() function will look for entry's section id which are already deleted..

### Steps to reproduce

1. Create a Channel section.
2. Add a new entry in the Channel.
3. Promote a live version and then make a draft.
4. Change the Channel to a Structure.
5. Access the drafts in workflow setting.

### Additional info

- Plugin version: 1.2.3
- Craft version: Craft Pro 3.3.2

**Comment by JoeyNK** [comment]
I am experiencing the same issue on a test site we are currently building.  I can browse the "Overview" and "Settings" tabs without any problem. But accessing the "Drafts" tab results in an "Invalid Section ID: " exception.

I hope someone replies to this thread.

**Comment by matthewmrotter** [comment]
We're having the same issue as well 

Plugin version: 1.2.3
Craft version: Craft Pro 3.3.6

**Comment by matthewmrotter** [comment]
We managed to fix it by searching the database for the deleted section, then finding entries that were part of that section and deleting those rows

**Comment by britteninc** [comment]
I am trying this plugin now and experiencing the same issue. Looking to get this resolved so I can purchase and deploy it to our production server...

**Comment by engram-design** [comment]
I'm actually removing the Drafts screen altogether now as its now included in Craft core. In previous version of Craft, it was pretty tedious to see all draft entries, as you'd have to go into each specific entry and look at the version/site dropdown.

Now - you can go to any section, and change the status dropdown from Live to Drafts. As such, this screen is being deprecated (removed) in [1.3.0](https://github.com/verbb/workflow/releases/tag/1.3.0)
