### ISSUE TITLE
"save draft and submit for approval" button doesn't work on multisite the way it does on the default site

### ISSUE THREAD

**Issue by knynkwl** [engram-design/Workflow#91]
### Description
When clicking "save draft and submit for approval" it adds the entry to the drafts list on the workflow page, but when clicking into the actual entry it doesn't do to the draft, it goes to its current state.

A workaround I found was, instead of clicking "save draft and submit for approval" first, the user can click "Save Draft" and then add a note and click "save draft and submit for approval" and it works as intended.

### Additional info

- Plugin version: 1.2.3
- Craft version: 3.2.10

**Comment by engram-design** [comment]
We've updated some behaviour in [1.3.0](https://github.com/verbb/workflow/releases/tag/1.3.0) to fix this!
