### ISSUE TITLE
Autosave: Should be disabled when entry submitted for review

### ISSUE THREAD

**Issue by d--j** [engram-design/Workflow#93]
### Description

Craft 3.2 introduced autosaving changes of a draft. Workflow should disable/prevent this autosaving when the draft was submitted for review. Otherwise the editors can make changes after submission for review.

### Steps to reproduce

1. Editor submits a draft for review.
2. Its status is "Awaiting approval" and info text says "This entry has been submitted for review on ... and is awaiting approval. **Changes cannot be made until approved.**"
3. The editor can still  make changes

The code that should prevent further editing
https://github.com/verbb/workflow/blob/a3cbb2b65ee88b8bef6a15b879292c325d119d01/src/templates/_includes/editor-pane.html#L161-L184
needs to be updated to work with autosaving - Craft 3.2 does not have a `#main #header .btn.submit` button anymore and doesn't do normal form submits.

### Additional info

- Plugin version: 1.2.3
- Craft version: Craft Pro 3.3.14 (Autosave was introduced in Craft 3.2)

**Comment by engram-design** [comment]
Yep, good thinking here. This should be fixed in [1.3.0](https://github.com/verbb/workflow/releases/tag/1.3.0)

I will point out that this code is required still, in that it hides the Save button, but extra work to cater for auto-saving is completely valid.
