### ISSUE TITLE
Email event hooks failing

### ISSUE THREAD

**Issue by dictions** [engram-design/Workflow#97]
### Description

Hey there. I'm trying to get email event hooks to fire. While the `EVENT_BEFORE_SAVE` event works, neither hooks for the editor email nor the publisher email work. After hooking into the email events, sending the email fails as such:

```
2019-11-20 12:22:06 [-][1690][-][info][workflow] Failed to send publisher notification to ian+stripesreviewer@gardener.nyc - Class 'verbb\workflow\services\EmailEvent' not found
```

### Steps to reproduce

I've created a gist of my hook plugin, available here:
https://gist.github.com/dictions/a5a77cd6a8cc4a1c5457b5c34b6ca4c1

### Additional info

- Plugin version: 1.2.3
- Craft version: 3.3.15

**Comment by engram-design** [comment]
This should be fixed in [1.3.0](https://github.com/verbb/workflow/releases/tag/1.3.0)
