### ISSUE TITLE
Error approving entry

### ISSUE THREAD

**Issue by umkasanki** [engram-design/Workflow#99]
### Description

The first attempt to change the status of a record always causes an error. On the second attempt, the status changes. Screen record https://youtu.be/Pvwyz0rvutI
[logs.zip](https://github.com/verbb/workflow/files/4082322/logs.zip)

### Steps to reproduce

1. Submit new submission
2. Try to approve 

### Additional info

- Plugin version: 1.3.2
- Craft version: Pro 3.3.20.1 (multisite)

**Comment by engram-design** [comment]
Should be fixed in [1.3.3](https://github.com/verbb/workflow/releases/tag/1.3.3)
